<?
// -------- start v0.1b template section -----------
// admin.php Main section
$lang_admin_1 = "Password";
$lang_admin_2 = "Admin Panel";
$lang_admin_3 = "Admin Login";
$lang_admin_4 = "Setup Sections";
$lang_admin_5 = "settings";
$lang_admin_6 = "Category(es)";
$lang_admin_7 = "Blacklists";
$lang_admin_8 = "statistics";
$lang_admin_9 = "Total";
$lang_admin_10 = "Post(s)";
$lang_admin_11 = "Approved";
$lang_admin_12 = "Waiting";
$lang_admin_13 = "mail(s) in Maillist";
$lang_admin_14 = "Last update base";
$lang_admin_15 = "E-Mail";
$lang_admin_16 = "Url";
$lang_admin_17 = "Description";
$lang_admin_18 = "Referer";
$lang_admin_19 = "IP";
$lang_admin_20 = "Block by";
$lang_admin_21 = "Save done";
$lang_admin_22 = "Admin password";
$lang_admin_23 = "Admin Mail";
$lang_admin_24 = "TGP Name";
$lang_admin_25 = "Language file";
$lang_admin_26 = "PhpMyTGP Setup Dir";
$lang_admin_27 = "TGP Main FileName";
$lang_admin_28 = "TGP Main Dir";
$lang_admin_29 = "TGP Main URL";
$lang_admin_30 = "Path to SENDMAIL";
$lang_admin_31 = "Length of LIST template field";
$lang_admin_32 = "Auto validate post";
$lang_admin_33 = "E-Mail functions ON/OFF";
$lang_admin_34 = "Precheck postings";
$lang_admin_35 = "Daily Max Post per Domain";
$lang_admin_36 = "Daily Max Post per E-Mail";
$lang_admin_37 = "Rebuild Time";
$lang_admin_38 = "Rotate Days";
$lang_admin_39 = "Check Frase";
$lang_admin_40 = "don't worry";
$lang_admin_41 = "minutes";
$lang_admin_42 = "days";
$lang_admin_43 = "Delete category result";
$lang_admin_44 = "with trailing slash";
$lang_admin_45 = "was deleted.";
$lang_admin_46 = "is not in Category List";
$lang_admin_47 = "Mark Category field";
$lang_admin_48 = "Add category result";
$lang_admin_49 = "was added.";
$lang_admin_50 = "already in Category List";
$lang_admin_51 = "Category field empty";
$lang_admin_52 = "Add Black List Field result";
$lang_admin_53 = "Blacklist Rule";
$lang_admin_54 = "was added to Blacklist List";
$lang_admin_55 = "already in Blacklist List";
$lang_admin_56 = "Blacklist field empty";
$lang_admin_57 = "Delete Field result";
$lang_admin_58 = "was deleted from Black List";
$lang_admin_59 = "is not in Black List";
$lang_admin_60 = "Mark Blacklist pattern field";
$lang_admin_61 = "MAILLIST SETUP SECTION";
$lang_admin_62 = "Add mail result";
$lang_admin_63 = "already in MailList";
$lang_admin_64 = "Mail field empty";
$lang_admin_65 = "Delete mail result";
$lang_admin_66 = "Mark Mail for delete from List";
$lang_admin_67 = "TEMPLATES SETUP SECTION";
$lang_admin_68 = "Template files";
$lang_admin_69 = "You can use this template tag(s)";
$lang_admin_70 = "Save template result";
$lang_admin_71 = "bytes write success.";
$lang_admin_72 = "POST MENU SECTION";
$lang_admin_73 = "EDIT POST SECTION";
$lang_admin_74 = "pics";
$lang_admin_75 = "Result";
$lang_admin_76 = "Delete post result";
$lang_admin_77 = "Mark Post for delete from List";
$lang_admin_78 = "Validate post result";
$lang_admin_79 = "validated now.";
$lang_admin_80 = "Mark Post for validation from List";
$lang_admin_81 = "Rebuild result";
$lang_admin_82 = "From";
$lang_admin_83 = "Subj";
$lang_admin_84 = "Message body";
$lang_admin_85 = "Something wrong during sending mail!";
$lang_admin_86 = "Sending mail done.";
$lang_admin_87 = "Validated";
$lang_admin_88 = "Select post for edit";
$lang_admin_89 = "Date";
$lang_admin_90 = "Referer";
$lang_admin_91 = "Delete";
$lang_admin_92 = "Post saved.";

$lang_error_1 = "Update query failed. Query:";
$lang_error_2 = "Wrong E-Mail address";
$lang_error_3 = "Can't Open template file";
$lang_error_4 = "Can't write to template file";
$lang_template_join = "This places a link to the submission form after they have agreed to your terms & conditions";
// -------- end v0.1b template section -----------

// -------- start v0.3b template section -----------
// admin.php Main section
$lang_admin_93 = "Author!";
$lang_admin_94 = "Forbid window.open script";
$lang_admin_95 = "Date";
// -------- end v0.3b template section -----------

// -------- start v0.4 template section -----------
// admin.php Main section
$lang_admin_96 = "VIP";
$lang_admin_97 = "Use VIP Posts?";
$lang_admin_98 = "Stay VIP First?";
$lang_admin_99 = "VIP SETUP SECTION";
$lang_admin_100 = "VIP posts only";
$lang_admin_101 = "Submissions Rules";
$lang_admin_102 = "Daily Max Post per Category";
$lang_admin_103 = "VIP Settings";
$lang_admin_104 = "Checking Postings";
$lang_admin_105 = "Forbid change Status string";
$lang_admin_106 = "Forbid onMouse script";
$lang_admin_107 = "Forbid onClick script";
$lang_admin_108 = "Delete all posts from base where";

// add.php 
$lang_interface1 = "too many daily post per E-Mail";
$lang_interface2 = "too many daily post in one category";
$lang_interface3 = "Can't query: ";
$lang_interface4 = "Can't open template";
// -------- end v0.4 template section -----------
?>