document.writeln('<div align="center">')
document.writeln('<!--TopList COUNTER--><script language="JavaScript"><!--')
document.writeln('d=document;a=\'\';a+=\';r=\'+escape(d.referrer)')
document.writeln('js=10//--></script><script language="JavaScript1.1"><!--')
document.writeln('a+=\';j=\'+navigator.javaEnabled()')
document.writeln('js=11//--></script><script language="JavaScript1.2"><!--')
document.writeln('s=screen;a+=\';s=\'+s.width+\'*\'+s.height')
document.writeln('a+=\';d=\'+(s.colorDepth?s.colorDepth:s.pixelDepth)')
document.writeln('js=12//--></script><script language="JavaScript1.3"><!--')
document.writeln('js=13//--></script><script language="JavaScript"><!--')
document.writeln('d.write(\'<a href="http://top.list.ru/jump?from=15648"\'+')
document.writeln('\' target=_top><img src="http://top.list.ru/counter\'+')
document.writeln('\'?id=15648;t=34;js=\'+js+a+\';rand=\'+Math.random()+')
document.writeln('\'" alt="TopList"\'+\' border=0 height=31 width=88></a>\')')
document.writeln('if(js>11)d.write(\'<\'+\'!-- \')//--></script><noscript><a')
document.writeln('target=_top href="http://top.list.ru/jump?from=15648"><img')
document.writeln('src="http://top.list.ru/counter?js=na;id=15648;t=34"')
document.writeln('border=0 height=31 width=88')
document.writeln('alt="TopList"></a></noscript><script language="JavaScript"><!--')
document.writeln('if(js>11)d.write(\'--\'+\'>\')//--></script><!--TopList COUNTER-->')
document.writeln('<!--NEW1000CODE-->')
document.writeln('<script language="JavaScript"><!--')
document.writeln('var d=document,pw=self,js=10,a="",rfr=d.referrer;')
document.writeln('with(location)hst=href.substr(0,href.length-pathname.length)')
document.writeln('for (i=0;i<5;i++) {if(rfr.indexOf(hst)!=0)break;pw=pw.parent;rfr=pw.document.referrer;if(pw!=pw.parent)break;}')
document.writeln('a+="&r="+escape(rfr)')
document.writeln('//-->')
document.writeln('</script>')
document.writeln('<script language="JavaScript1.1"><!--')
document.writeln('js=11;a+="&j="+navigator.javaEnabled()')
document.writeln('//-->')
document.writeln('</script>')
document.writeln('<script language="JavaScript1.2"><!--')
document.writeln('js=12;s=screen;a+="&s="+s.width+"*"+s.height;a+="&d="+(s.colorDepth?s.colorDepth:s.pixelDepth)')
document.writeln('//-->')
document.writeln('</script>')
document.writeln('  <script language="JavaScript1.3"><!-- js=13 ')
document.writeln('  //-->')
document.writeln('</script>')
document.writeln('  <script language="JavaScript"><!--')
document.writeln('d.write("<img border=0 width=1 height=1 src=http://1000stars.ru/cgi-bin/1000f.cgi?id=kiporuksite&t=j11&js="+js+a+">");')
document.writeln('//-->')
document.writeln('</script>')
document.writeln('  <noscript><img src="http://1000stars.ru/cgi-bin/1000f.cgi?id=kiporuksite&t=j11&js=0" height=1 width=1></noscript> ')
document.writeln('  <!--ENDNEW1000CODE-->')
document.writeln('  <a href="http://www.stars.ru"><img src="http://1000stars.ru/cgi-bin/1000.cgi?kiporuksite" width=50 height=30 border=0></a> ')
document.writeln('    <!-- BEGIN Top 100  09.OPEN.BY CODE - ALTERNATING THIS CODE WILL CAUSE TERMINATION ACCOUNT-->')
document.writeln('    <a href="http://www.09.open.by/"> <img src="http://www.09.open.by/cgi-bin/info09counter.cgi?id=10002921" border="0" width="90" height="32" alt="Top 100  09.OPEN.BY"></a> ')
document.writeln('    <!-- END Top 100  09.OPEN.BY CODE-->')
document.writeln('    <!-- START OF ADDME LINK -->')
document.writeln('    <a href="http://www.addme.com"><img width="88" height="31" src="http://www.addme.com/link8.gif" alt="Add Me!" border="0"></a> ')
document.writeln('    <!-- END OF ADDME LINK -->')
document.writeln('    <!--begin of SUPERTOP code *** ID:955704284 ***-->')
document.writeln('    <a href="http://www.supertop.ru"><img src="http://supertop.ru/cgi-bin/supertop/nph-supertop?A=955704284" alt="SUPERTOP" width=88 height=31 border=0></a> ')
document.writeln('    <!--end of SUPERTOP code-->')
document.writeln('    <a href="http://br.gis.com.by/rate.cgi?0587"><img src="http://br.gis.com.by/newbutt4.cgi?0587" border=0 width=88 height=31 alt="Áåëîðóññêèé ðåéòèíã"></a> ')
document.writeln('    <a href="http://www.ranker.ru/scripts/sqltmex.dll?tpl=_top_tod_yest.htm&id=26055&category=8&sort=today%2Bdesc&page=1"><img src="count203.gif" alt="Aport Ranker" border="0"></a> ')
document.writeln('    <!--begin of Top100 logo-->')
document.writeln('    <a href="http://top100.rambler.ru/top100/"><img src="http://top100-images.rambler.ru/top100/banner-88x31-rambler-black2.gif" alt="Rambler s Top100" width=88 height=31 border=0></a>')
document.writeln('    <!--end of Top100 logo -->')
document.writeln('    <br><font size="2"><i> ')
document.writeln('  </i></font></div>')
document.writeln('<p align="center"><font size=2>©2001 <a href="mailto:skorostel@mail.ru">Sergey Korostel</a>, <a href="mailto:kaa_box@mail.ru">Anatoli Kiparuk</a> ')
document.writeln('    <script language="JavaScript">document.writeln("&nbsp;&nbsp; Ïîñë. ìîäèô. ",document.lastModified.fontcolor("000080"),"   "); ')
document.writeln('    </script></font></p>')
