<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="570" height="360" align="center" class="main_bold">
Are you sure you want to delete this staff member?
<br>
<br>
<button onclick="window.location='deletestaff.php?id=<?php echo $id ?>&delete=yes&confirm=yes'" class="formfield">Yes</button>
&nbsp;
<button onclick="window.location='deletestaff.php?id=<?php echo $id ?>&delete=yes&cancel=yes'" class="formfield">No</button>
</td>
</tr>
</table>