<table width="570" border="0" cellspacing="0" cellpadding="2" class="main_bold" style="border: 1 solid #000000">
<tr>
<td width="570" colspan="3" align="center">
<button onclick="history.go(-1);" class="formfield">Back</button>
</td>
</tr>
<tr>
<td width="50">
ID:
</td>
<td width="350">
Name: (Click To View)
</td>
<td width="170">
Access Level:
</td>
</tr>
<?php include ("$rootdirectory/admin/staffmanager/viewallstaff.inc"); ?>
</table>