<script language="JavaScript">

<!-- Cloak Engaged

//MSIE 4.x Detection

  if ((navigator.appName == "Microsoft Internet Explorer") && (parseInt(navigator.appVersion) >= 4 ))

     {}

  else

     {alert("Diese Seiten sind fuer den MS Internet Explorer 4.0 und hoeher, 800x600 oder hoeher optimiert ! Du benutzt einen anderen Browser, die Seiten werden moeglicherweise nicht korrekt angezeigt !!!");}

//-- Cloak Disengaged -->

</script>



