<div class="mainheader">Best&auml;tigt</div>

<div class="maintext">

<br>

DANKE,  <? echo $nick; ?><br><br>

Deine Anmeldung ist nun best&auml;tigt.

Du bist nun als vollwertiges Mitglied in unserer Datenbank eingetragen.<br>

<br>

Du kannst Dich nun mit Deinem Usernamen und Passwort einloggen.<br>

<br><center>

<input type=submit value="zur Hauptseite" onClick="window.location.href='main.php'">

<input type=submit value="Schliessen" onClick="window.close()">

</center>

</div>

