<table><tr><td colspan="2">

treten Sie mit <em id="red">smartisoft.com</em> in Kontakt.<br>

<br>

</td></tr>

<tr><td>

Webmaster :

</td><td>

<a href="mailto:webmaster@smartisoft.com">webmaster@smartisoft.com</a><br>

</td></tr>

<tr><td>

Support   :

</td><td>

<a href="mailto:support@smartisoft.com">support@smartisoft.com</a><br>

</td></tr>

<tr><td>

Marketing :

</td><td>

<a href="mailto:marketing@smartisoft.com">marketing@smartisoft.com</a><br>

</td></tr>

<tr><td>

Allgemein    :

</td><td>

<a href="mailto:office@smartisoft.com">office@smartisoft.com</a><br>

</td></tr>

<tr><td><br>

Standort  :

</td><td><br>

Erde<br>

</td></tr>

<tr><td valign="top">

Software  :

</td><td>

phpBazar <? echo $bazar_version?><br></td></tr>

<br>

</table>