<option value="0">-------------------------</option>

<option value="A - Burgenland">A - Burgenland</option>

<option value="A - Kärnten">A - Kärnten</option>

<option value="A - Niederösterreich">A - Niederösterreich</option>

<option value="A - Oberösterreich">A - Oberösterreich</option>

<option value="A - Salzburg">A - Salzburg</option>

<option value="A - Steiermark">A - Steiermark</option>

<option value="A - Tirol">A - Tirol</option>

<option value="A - Wien">A - Wien</option>

<option value="A - Vorarlberg">A - Vorarlberg</option>

<option value="0">-------------------------</option>

<option value="D - Bremen">D - Bremen</option>

<option value="D - Baden-Württemberg">D - Baden-Württemberg</option>

<option value="D - Bayern">D - Bayern</option>

<option value="D - Berlin">D - Berlin</option>

<option value="D - Brandenburg">D - Brandenburg</option>

<option value="D - Hamburg">D - Hamburg</option>

<option value="D - Hessen">D - Hessen</option>

<option value="D - Saarland">D - Saarland</option>

<option value="D - Rheinland-Pfalz">D - Rheinland-Pfalz</option>

<option value="D - Schleswig-Holstein">D - Schleswig-Holstein</option>

<option value="D - Sachsen">D - Sachsen</option>

<option value="D - Sachsen-Anhalt">D - Sachsen-Anhalt</option>

<option value="D - Thüringen">D - Thüringen</option>

<option value="D - Nordrhein-Westfalen">D - Nordrhein-Westfalen</option>

<option value="D - Niedersachsen">D - Niedersachsen</option>

<option value="D - Mecklenburg-Vorpommern">D - Mecklenburg-Vorpommern</option>

<option value="0">-------------------------</option>

<option value="CH - Aargau">CH - Aargau</option>

<option value="CH - Appenzell A.-Rh.">CH - Appenzell A.-Rh.</option>

<option value="CH - Appenzell I.-Rh.">CH - Appenzell I.-Rh.</option>

<option value="CH - Basel-Stadt">CH - Basel-Stadt</option>

<option value="CH - Basel-Land">CH - Basel-Land</option>

<option value="CH - Bern">CH - Bern</option>

<option value="CH - Freiburg">CH - Freiburg</option>

<option value="CH - Genf">CH - Genf</option>

<option value="CH - Glarus">CH - Glarus</option>

<option value="CH - Graubünden">CH - Graubünden</option>

<option value="CH - Luzern">CH - Luzern</option>

<option value="CH - Neuenburg">CH - Neuenburg</option>

<option value="CH - Sankt Gallen">CH - Sankt Gallen</option>

<option value="CH - Schaffhausen">CH - Schaffhausen</option>

<option value="CH - Schwyz">CH - Schwyz</option>

<option value="CH - Solothurn">CH - Solothurn</option>

<option value="CH - Tessin">CH - Tessin</option>

<option value="CH - Thurgau">CH - Thurgau</option>

<option value="CH - Obwalden">CH - Obwalden</option>

<option value="CH - Nidwalden">CH - Nidwalden</option>

<option value="CH - Uri">CH - Uri</option>

<option value="CH - Waadt">CH - Waadt</option>

<option value="CH - Wallis">CH - Wallis</option>

<option value="CH - Zug">CH - Zug</option>

<option value="CH - Zürich">CH - Zürich</option>

<option value="0">-------------------------</option>

<option value="Baltische Staaten">Baltische Staaten</option>

<option value="Belgien">Belgien</option>

<option value="Dänemark">Dänemark</option>

<option value="England">England</option>

<option value="Frankreich">Frankreich</option>

<option value="Griechenland">Griechenland</option>

<option value="Irland">Irland</option>

<option value="Italien">Italien</option>

<option value="Luxemburg">Luxemburg</option>

<option value="Niederlande">Niederlande</option>

<option value="Norwegen">Norwegen</option>

<option value="Polen">Polen</option>

<option value="Portugal">Portugal</option>

<option value="Rußland">Rußland</option>

<option value="Slowakische Rep.">Slowakische Rep.</option>

<option value="Spanien">Spanien</option>

<option value="Schweden">Schweden</option>

<option value="Tschechische Rep.">Tschechische Rep.</option>

<option value="Türkei">Türkei</option>

<option value="Ungarn">Ungarn</option>

<option value="0">-------------------------</option>

<option value="USA">USA</option>

<option value="Kanada">Kanada</option>

<option value="Australien">Australien</option>

<option value="Indien">Indien</option>

<option value="Japan">Japan</option>

<option value="New Zealand">New Zealand</option>

<option value="Afrika">Afrika</option>

<option value="Süd-Amerika">Süd-Amerika</option>

<option value="Mittlerer Osten">Mittlerer Osten</option>

<option value="Andere">Andere</option>

