<div class="mainheader">Danke<p><div>

<div class="maintext">

<br>

Du bist nun registriert (Warten auf Best&auml;tigung). <br>

Wir haben eine E-Mail an <b><? echo "$email";?></b> gesandt<br>

<br>

Du musst nun Deinen Posteingang &uuml;berpr&uuml;fen und auf den in der E-Mail angegeben Link klicken

um Deine Anmeldung zu best&auml;tigen. Geschieht dies nicht innerhalb der n&auml;chsten 48 Stunden, wird Deine Anmeldung gel&ouml;scht.

<br>

<br><center><form action=javascript:window.close() METHOD=POST>

<input type=submit value=Schliessen></form></center>

</div>

