<br>

<DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">



<html>

 <head>

   <title>Nutzungsbedingungen</title>

     <link rel="stylesheet" type="text/css" href="<? echo $STYLE; ?>">

      <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">

 </head>



<?echo"<body bgcolor=\"$bgcolor\">\n";?>



<div class="maintext">

Nutzungsbedingungen<br><br>

hier stehen Ihre Nutzungsbedingungen<br><br>

</div>

</body>

</html>



