<h3 align="right">Willkommen</h3>

<p align="justify">

... bei <em id="red">phpBazar</em> !<br>

<br>

Das ist die Willkommen-Seite von phpBazar<br>

<br>

Sollte diese Seite Erwachsenen-Inhalte haben, w&auml;re ein AltersCheck hier nicht schlecht - zumindest eine Frage :-)<br>

<br>

Um auf unsere Seiten zu gelangen registriert Euch bitte kostenlos mit einem Nick (Spitzname) !<br>

</p>

<p align="right">

<a href="http://www.disney.com" target="_self">NEIN, das ist nichts f&uuml;r mich!</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

<a href="main.php" target="_self">JA, ich will und darf weiter</a>

</p>



