<?
/*
***************************************************
***************************************************
*          :: PHP Super Counter v1.03 ::          *
* Coded by Roel S.F. Abspoel (roel@abspoel.com)   *
***************************************************
*    Magtrb.com  13/11/05 21:12
*http://www.magtrb.com/Scripts/pafiledb.php?action=category&id=77
* you can post any new ideas or comments at
*http://www.magtrb.com/Invision/index.php?s=&act=SF&f=9
* no need for registration to post just post directlly in english.
***************************************************     */

?>

<HTML><HEAD>
<script language="JavaScript">
<!--
<!-- Begin
function printPage() {
  window.print();
}
//  End -->

function MM_callJS(jsStr) { //v2.0
  return eval(jsStr)
}
//-->
</script>
<?PHP INCLUDE"sc_information.php"; ?>
<title>Super Counter :: Statistics</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="Author" content="Roel S.F. Abspoel,Magtrb.com">
<meta name="Publisher" content="Roel S.F. Abspoel,Magtrb.com">
<meta name="Copyright" content="© 2003">
<meta name="Keywords" content="super,counter,php,statistics,hits,counter,country,browser,refferer,page">
<meta name="Description" content="These statistics are generated by PHP Super Counter v1.03 by Magtrb.com, http://www.magtrb.com/Scripts/pafiledb.php?action=category&id=77">
<meta name="Page-topic" content="PHP Super Counter :: Statistics">
<meta name="Audience" content="All">
<meta name="Content-language" content="EN">
<meta name="Page-type" content="Statistics">
<meta name="Robots" content="INDEX,FOLLOW">
</HEAD>
<BODY bgcolor="#EEEEEE" text="#000066" link="#990000" vlink="#990000" alink="#000066">
<div align="center"><b><font color="#000000" size="7">
  <a name="global"></a></font></b> 
  <table width="80%" border="1" cellspacing="0" cellpadding="0" bordercolor="#000000">
    <tr> 
      <td bgcolor="#FFFFFF" valign="middle">
        <div align="center"> 
          <p><b><font color="#000000" size="7">:: Super Counter :: </font></b><font size="7"><b><font color="#000000">Statistics</font></b></font></p>
        </div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 

            <td width="100%">
              <p align="center"><b><font size="6" color="#000000"><b>Counting
                since:</b> <b><font color="#990000"> 
                <?PHP show_totalhits_countdate(); ?>
                </font></b></font></b></p>
              <p align="center"><b><font size="6" color="#000000">Total hits:</font></b><font size="6" color="#990000">
                </font> <b><font size="6" color="#990000"> 
                <?PHP show_totalhits(); ?>
                </font></b></p>
              <p align="center"><b><font color="#000000" size="7">
                <input type="submit" name="Submit" value="Print this page" onClick="MM_callJS('window.print();')">
                </font></b></p>
            </td>

          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF">
        <div align="center"><font size="2"><b><font color="#000000" size="4">Global
          statistics</font><font color="#000000"> - <a href="#country">Country
          statistics</a> - <a href="#os">Operating System statistics</a> - <a href="#browser">Browser 
          statistics</a> - <a href="#referer">Referer statistics</a> - <a href="#page">Page 
          count statistics</a></font></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF"> 
        <table border=0 width=100%>
          <tr> 
            <td width="28%"> 
              <div align="center"><font color="#000000"><b>Hits today:</b> </font><font size="4" color="#000000">
                <?PHP show_todayhits(); ?>
                </font></div>
            </td>
            <td width="38%"> 
              <div align="center"><font color="#000000"><b>Hits this month: </b></font><font size="4" color="#000000">
                <?PHP show_thismonthhits(); ?>
                </font><font color="#000000"> </font></div>
            </td>
            <td width="34%"> 
              <div align="center"><font color="#000000"><b>Currently online:</b>
                </font><font size="4" color="#000000">
                <?PHP show_currentlyonline();?>
                </font><font color="#000000"> </font></div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF">
        <div align="center"><font color="#990000"><b>Monthly hits</b></font></div>
      </td>
    </tr>
    <tr> 
      <td> 
        <div align="center"><b><font size="4" color="#000000">
          <?PHP show_monthhits(); ?>
          </font><font color="#990000"></font></b></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF">
        <div align="center"><font color="#990000"><b>Daily hits</b></font></div>
      </td>
    </tr>
    <tr> 
      <td>
        <div align="center"><font size="4" color="#000000">
          <?PHP show_dailyhits(); ?>
          </font></div>
      </td>
    </tr>
    <tr> 
      <td> 
        <div align="center"><font color="#000000">The statistics below this line
          are generated from the traffic in the last 24 hours:</font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF">
        <div align="center"><font size="2"><b><font color="#000000"><a name="country"></a></font><font size="2"><b><font color="#000000"><a href="#global">Global
          statistics</a> - <font size="4">Country statistics</font> - <a href="#os">Operating 
          System statistics</a> - <a href="#browser">Browser statistics</a> - 
          <a href="#referer">Referer statistics</a> - <a href="#page">Page count 
          statistics</a></font></b></font></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF"> <font color="#000000">
        <?PHP show_countryhits(); ?>
        </font></td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF">
        <div align="center"><font size="2"><b><font color="#000000"><a name="os"></a></font><font size="2"><b><font color="#000000"><a href="#global">Global
          statistics</a> - <a href="#country">Country statistics</a> - <font size="4">Operating 
          System statistics</font> - <a href="#browser">Browser statistics</a> 
          - <a href="#referer">Referer statistics</a> - <a href="#page">Page count 
          statistics</a></font></b></font></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF"><font color="#000000">
        <?PHP show_oshits(); ?>
        </font></td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF">
        <div align="center"><font size="2"><b><font color="#000000"><a name="browser"></a></font><font size="2"><b><font color="#000000"><a href="#global">Global
          statistics</a> - <a href="#country">Country statistics</a> - <a href="#os">Operating 
          System statistics</a> - <font size="4">Browser statistics</font> - <a href="#referer">Referer 
          statistics</a> - <a href="#page">Page count statistics</a></font></b></font></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF"><font color="#000000">
        <?PHP show_browserhits(); ?>
        </font></td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF">
        <div align="center"><font size="2"><b><font color="#000000"><a name="referer"></a></font><font size="2"><b><font color="#000000"><a href="#global">Global
          statistics</a> - <a href="#country">Country statistics</a> - <a href="#os">Operating 
          System statistics</a> - <a href="#browser">Browser statistics</a> - 
          <font size="4">Referer statistics</font> - <a href="#page">Page count 
          statistics</a></font></b></font></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF"><font color="#000000">
        <?PHP show_referrerhits(); ?>
        </font></td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF">
        <div align="center"><font size="2"><b><font color="#000000"><a name="page"></a></font><font size="2"><b><font color="#000000"><a href="#global">Global
          statistics</a> - <a href="#country">Country statistics</a> - <a href="#os">Operating 
          System statistics</a> - <a href="#browser">Browser statistics</a> - 
          <a href="#referer">Referer statistics</a> - <font size="4">Page count 
          statistics</font></font></b></font></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF"><font color="#000000">
        <?PHP show_pagehits(); ?>
        </font></td>
    </tr>
    <tr> 
      <td bgcolor="#FFFFFF" valign="middle">
        <div align="center"> 
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr> 
              <td width="100%">
                <div align="center"><font color="#000000"><b>:: <a href="http://www.abspoel.com/roel-karin/download.php" target="_blank">PHP
                  Super Counter</a> version 1.01 &copy; 2003 <a href="http://www.abspoel.com/roel-karin/response.php" target="_blank">Roel 
                  S.F. Abspoel</a> :: </b></font></div>
              </td>

            </tr>
            <tr>
              <td width="100%">
                <div align="center"><font color="#000000"><b>:: <a href="http://www.magtrb.com/Scripts/pafiledb.php?action=category&id=77" target="_blank">PHP
                  Super Counter</a> version 1.03 &copy; 2005 <a href="http://www.magtrb.com" target="_blank">Magtrb.com</a> :: </b></font></div>
              </td>

            </tr>

          </table>
        </div>
      </td>
    </tr>
  </table>
</div>
</BODY></HTML>
