<div class="mainheader">Best&auml;tigt</div>

<div class="maintext">

<br>

DANKE,  <? echo $username; ?><br><br>

Ihre Anmeldung ist nun best&auml;tigt.

Sie sind nun als vollwertiges Mitglied in unserer Datenbank eingetragen.<br>

<br>

Sie k&ouml;nnen sich nun mit Ihrem Usernamen und Passwort einloggen.<br>

<br><center><form action=javascript:window.close() METHOD=POST>

<input type=submit value=Schliessen></form></center>

</div>

