CREATE TABLE clients (
  id int(4) NOT NULL auto_increment,
  surname varchar(20) default NULL,
  firstname varchar(20) default NULL,
  telephone varchar(20) default NULL,
  email varchar(30) default NULL,
  icq varchar(10) default NULL,
  referrer varchar(20) default NULL,
  house varchar(20) default NULL,
  street varchar(50) default NULL,
  town varchar(50) default NULL,
  state varchar(20) default NULL,
  country varchar(20) default NULL,
  postcode varchar(10) default NULL,
  domainname varchar(20) default NULL,
  domain varchar(10) default NULL,
  package varchar(100) default NULL,
  schedule varchar(11) default NULL,
  payment varchar(11) default NULL,
  username varchar(10) default NULL,
  password varchar(32) default NULL,
  ipaddress varchar(20) default NULL,
  startdate varchar(8) default NULL,
  invoicedate varchar(10) default NULL,
  duedate varchar(10) default NULL,
  amount varchar(10) default NULL,
  paid char(3) default NULL,
  status varchar(10) default NULL,
  notes varchar(255) default NULL,
  language varchar(50) default NULL,
  template varchar(50) default NULL,
  PRIMARY KEY (id),
  UNIQUE KEY id(id));

CREATE TABLE pending (
  id int(4) NOT NULL auto_increment,
  surname varchar(20) default NULL,
  firstname varchar(20) default NULL,
  telephone varchar(20) default NULL,
  email varchar(30) default NULL,
  icq varchar(10) default NULL,
  referrer varchar(20) default NULL,
  house varchar(20) default NULL,
  street varchar(50) default NULL,
  town varchar(50) default NULL,
  state varchar(20) default NULL,
  country varchar(20) default NULL,
  postcode varchar(10) default NULL,
  domainname varchar(20) default NULL,
  domain varchar(10) default NULL,
  package varchar(100) default NULL,
  schedule varchar(11) default NULL,
  payment varchar(11) default NULL,
  username varchar(10) default NULL,
  password varchar(32) default NULL,
  amount varchar(10) default NULL,
  PRIMARY KEY (id),
  UNIQUE KEY id(id));

CREATE TABLE plans (
  id int(4) NOT NULL auto_increment,
  package varchar(100) default NULL,
  monthly varchar(10) default NULL,
  quarterly varchar(10) default NULL,
  biannually varchar(10) default NULL,
  yearly varchar(10) default NULL,
  nochex_monthly varchar(255) default NULL,
  nochex_quarterly varchar(255) default NULL,
  nochex_biannually varchar(255) default NULL,
  nochex_yearly varchar(255) default NULL,
  paypal_monthly varchar(255) default NULL,
  paypal_quarterly varchar(255) default NULL,
  paypal_biannually varchar(255) default NULL,
  paypal_yearly varchar(255) default NULL,
  cc_monthly varchar(255) default NULL,
  cc_quarterly varchar(255) default NULL,
  cc_biannually varchar(255) default NULL,
  cc_yearly varchar(255) default NULL,
  KEY id(id));

CREATE TABLE staff (
  id int(4) NOT NULL auto_increment,
  adminname varchar(20) default NULL,
  password varchar(32) default NULL,
  access varchar(10) default NULL,
  language varchar(50) default NULL,
  template varchar(50) default NULL,
  PRIMARY KEY (id),
  UNIQUE KEY id(id));

INSERT INTO staff VALUES (1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 'Superadmin', 'english.inc', 'default');

CREATE TABLE support (
  ticketno int(4) NOT NULL auto_increment,
  username varchar(10) default NULL,
  email varchar(30) default NULL,
  url varchar(100) default NULL,
  subject varchar(255) default NULL,
  description longtext,
  status varchar(10) default NULL,
  admin varchar(20) default NULL,
  date varchar(16) default NULL,
  PRIMARY KEY (ticketno),
  UNIQUE KEY id(ticketno));

CREATE TABLE transactions (
  id int(4) default NULL,
  details varchar(255) default NULL,
  date varchar(8) default NULL);

CREATE TABLE variables (
  language varchar(30) default NULL,
  template varchar(30) default NULL,
  clientmanagerlogin_title varchar(100) default NULL,
  clientmanager_title varchar(100) default NULL,
  accountmanagerlogin_title varchar(100) default NULL,
  accountmanager_title varchar(100) default NULL,
  admin_email varchar(100) default NULL,
  accounts_email varchar(100) default NULL,
  supports_email varchar(100) default NULL,
  checkout_email varchar(100) default NULL,
  revecom_email varchar(100) default NULL,
  paypal_email varchar(100) default NULL,
  worldpay_email varchar(100) default NULL,
  company varchar(100) default NULL,
  processor varchar(50) default NULL,
  dateformat char(2) default NULL,
  instId varchar(10) default NULL,
  currency varchar(10) default NULL,
  worldpayPW varchar(20) default NULL,
  cp varchar(20) default NULL,
  currencytype char(1) default NULL);

INSERT INTO variables VALUES ('english.inc', 'default', 'phpManager - Staff Login', 'phpManager - Client Manager', 'phpManager - Client Login', 'phpManager - Account Manager', 'anything@yourdomain.com', 'anything@yourdomain.com', 'anything@yourdomain.com', 'anything@yourdomain.com', 'anything@yourdomain.com', 'anything@yourdomain.com', 'anything@yourdomain.com', 'YOUR COMPANY', 'None', 'US', 'Optional', 'Optional', 'Optional', 'None', '$');

