<?php

$access_denied = "Access denied";

$activationemail_password = "Your chosen password";
$activationemail_sent = "Activation email sent";

$add = "Add";

$back = "Back";

$date = "Date:";
$details = "Details:";
$domainmsg = "Domain:";

$user_taken = "Error, username has already been taken. Please choose another.";

$client_activated = "Client Has Been Activated.";
$client_added = "Client Has Been Added.";
$client_cancelled = "Client Cancelled.";
$client_confdel = "Are you sure you want to delete this client?";
$client_deleted = "Client has been deleted.";
$client_duedate = "Payment Due Date for Client ID:";
$client_edited = "Record Edited.";
$client_email = "All clients have been emailed.";
$client_emailsent = "An email has been sent to";
$client_error = "Error, unable to retrieve client details.";
$client_id = "Client ID:";
$client_modifypass = "Password Edited.";
$client_noinvoice = "No clients to invoice";
$client_nopending = "No clients pending";
$client_notactivated = "Client Not Activated. Please fill in all the required fields.";
$client_notadded = "Client Not Added. Please fill in all the required fields.";
$client_notfound = "Client ID not found.";
$client_nopending = "There are no Pending Clients to activate.";
$client_unpaid = "No clients still to pay";
$client_updated = "Client Records Have Been Updated.";
$client_updatedmsg = "Your contact details have been updated.";

$company_biannual = "Total number of Bi-Annual clients:";
$company_biannualincome = "Total income from Bi-Annual clients:";
$company_clients = "Total number of clients:";
$company_monthly = "Total number of monthly clients:";
$company_monthlyincome = "Total income from monthly clients:";
$company_quarterly = "Total number of quarterly clients:";
$company_quarterlyincome = "Total income from quarterly clients:";
$company_statistics = "Company Statistics";
$company_totalincome = "Total yearly income:";
$company_yearly = "Total number of yearly clients:";
$company_yearlyincome = "Total income from yearly clients:";

$dealtby = "Dealt By:";

$descriptionmsg = "Description:";

$domain_notfound = "Domain not found.";

$duedatemsg = "Payment Due Date:";

$edit = "Edit";

$email_activation = "Account Activation Email has been modified.";
$email_activationbcc = "Account ActivationBCC Email has been modified.";
$email_adminamend = "Admin Amend Support Email has been modified.";
$email_cancellation = "Account Cancellation Email has been modified.";
$email_chequeconfirmation = "Cheque Confirmation Email has been modified.";
$email_clientamend = "Client Amend Support Email has been modified.";
$email_closesupport = "Close Support Email has been modified.";
$email_ccconfirmation = "Credit Card Confirmation Email has been modified.";
$email_finalnotice = "Final Notice Email has been modified.";
$email_finalnoticebcc = "Final NoticeBCC Email has been modified.";
$email_invoice = "Invoice Email has been modified.";
$email_invoicerecord = "Invoice Record Email has been modified.";
$email_moniesconfirmation = "Monies Confirmation Email has been modified.";
$emailmsg = "Email:";
$email_neworder = "New Order Email has been modified.";
$email_nochexconfirmation = "NOCHEX Confirmation Email has been modified.";
$email_ordercancellation = "Order Cancellation Email has been modified.";
$email_paypalconfirmation = "PayPal Confirmation Email has been modified.";
$email_receipt = "Receipt Email has been modified.";
$email_submitted = "You email has been submitted. We will reply to your email as soon as possible.";
$email_support = "New Support Email has been modified.";
$email_supportnotice = "Support Notice Email has been modified.";

$fillfields = "Please fill in all the required fields.";

$finalnoticeemail_sent = "Final Notice Email Sent.";

$invoice_amount = "Amount Due:";
$invoice_amountreceived = "Amount Received:";
$invoice_changedate = "Invoice date for Client ID:";
$invoice_changed = "has been changed.";
$invoice_date = "Invoice Date:";
$invoice_duedate = "Payment Due Date:";
$invoice_message = "Show below is a summary of your invoice. A copy has also been emailed to you. Please
make your payment by the payment due date otherwise we may, at our sole discretion,
suspend your account until all monies owed are cleared. If you are paying by PayPal
or Credit Card, you need not take any further action.";
$invoice_method = "Payment Method:";
$invoice_notification = "Invoice Notification";
$invoice_query = "If you have any queries, or are unable to pay this invoice, please contact us by sending a support request as soon as possible.";
$invoice_receipt = "Customer Receipt";
$invoice_receiptmsg = "This receipt is to acknowledge that your payment has been received. A copy
has also been emailed to you.";
$invoice_regards = "Regards,";
$invoice_schedule = "Payment Schedule:";
$invoice_sent = "Customer invoice sent.";
$invoice_thankyou = "Thank you for your business,";

$links_ccmodified = "Credit Card Links Modified";
$links_nochexmodified = "NOCHEX Links Modified";
$links_paypalmodified = "PayPal Links Modified";

$login_error = "Error: You have entered a wrong Username/Password combination.";
$login_pass = "Please enter your password.";
$login_thankyou = "Thank you for logging in";
$login_user = "Please enter your username.";
$login_userpass = "Please enter your username and password.";

$newduedate = "Enter New Payment Due Date";
$newinvoicedate = "Enter New Invoice Date";
$newticket = "New Ticket";

$no = "No";

$notransactions = "There are no transactions on that date.";
$notransactionsmsg = "You do not have any transactions.";

$packagemsg = "Package:";

$plan_added = "Plan Added";
$plan_deleted = "Plan Deleted";
$plan_modified = "Plan Modified";
$plan_name = "Please enter the plan name";

$search = "Search";

$searchtransactiondate = "Search by Date:";

$showallmsg = "Show All";

$staff_added = "Staff Member Added.";
$staff_deleted = "Staff member has been deleted.";
$staff_edited = "Staff Member Edited.";
$staff_error = "Error, unable to retrieve staff details.";
$staff_modifypass = "Password Edited.";
$staff_notadded ="Staff Member Not Added. Please fill in all the required fields.";
$staff_notfound = "Staff ID not found.";

$statusmsg = "Status:";

$subjectmsg = "Subject:";

$support_assigned = "Assigned Support Requests";
$support_close = "Close Ticket";
$support_closed = "Support request closed.";
$support_closedmsg = "This support request has been closed.";
$support_description = "Add to description";
$support_email = "An email has also been sent to the supplied address.";
$support_enter = "Please enter your addition to the support request.";
$support_error = "Error, unable to find ticket number. Please re-enter.";
$support_fields = "Please fill in all the required fields.";
$support_modified = "The support request has been modified.";
$support_new = "New Support Requests";
$support_noassigned = "No assigned support requests";
$support_nonew = "No new support requests";
$support_received = "Your support request has been received and will be assigned to a member of our support team as soon as possible.";
$support_regards = "Regards,";
$support_resolved = "Your support request has been resolved. Thank you for using our Support Ticket System.";
$support_submit = "Thank you for submitting your support request. Your ticket number is:";
$support_team = "Support Team";
$support_thankyou = "Thank you for using our Support Ticket System";

$time = "Time:";

$ticketnumber = "Ticket Number:";

$update = "Update";
$usernamemsg = "Username:";
$username_notfound = "Username not found.";

$variables_modified = "Variables Modified";

$viewticket = "View Ticket";

$webaddress = "URL:";

$yes = "Yes";

?>