<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="285" valign="top" align="center" class="main">
<table width="280" border="0" cellspacing="0" cellpadding="2" class="main_bold" style="border: 1 solid #000000">
<tr>
<td width="285" align="center" class="summary_message">
- Account Emails -
</td>
</tr>
<tr>
<td width="285" valign="top" align="center" class="main">
<b><a href='<?php echo $PHP_SELF ?>?activation=yes' class='link'>Account Activation Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?cancel=yes' class='link'>Account Cancellation Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?invoice=yes' class='link'>Invoice Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?receipt=yes' class='link'>Receipt Email</a></b>
</td>
</tr>
</table>
</td>
<td width="285" valign="top" align="center" class="main">
<table width="280" border="0" cellspacing="0" cellpadding="2" class="main_bold" style="border: 1 solid #000000">
<tr>
<td width="285" align="center" class="summary_message">
- Support Emails -
</td>
</tr>
<tr>
<td width="285" align="center" class="main">
<b><a href='<?php echo $PHP_SELF ?>?adminamend=yes' class='link'>Admin Amend Support Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?clientamend=yes' class='link'>Client Amend Support Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?closesupport=yes' class='link'>Close Support Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?newsupport=yes' class='link'>New Support Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?supportnotice=yes' class='link'>Support Notice Email</a></b>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="285" valign="top" align="center" class="main">
<table width="280" border="0" cellspacing="0" cellpadding="2" class="main_bold" style="border: 1 solid #000000">
<tr>
<td width="285" align="center" class="summary_message">
- New Order Emails -
</td>
</tr>
<tr>
<td width="285" align="center" class="main">
<b><a href='<?php echo $PHP_SELF ?>?cheque=yes' class='link'>Cheque Confirmation Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?creditcard=yes' class='link'>Credit Card Confirmation Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?monies=yes' class='link'>Monies Confirmation Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?neworder=yes' class='link'>New Order Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?nochex=yes' class='link'>NOCHEX Confirmation Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?cancelorder=yes' class='link'>Order Cancellation Email</a>
<br>
<b><a href='<?php echo $PHP_SELF ?>?paypal=yes' class='link'>PayPal Confirmation Email</a></b>
</td>
</tr>
</table>
</td>
<td width="285" valign="top" align="center" class="main">
&nbsp;
</td>
</tr>
</table>