<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="570" height="360" align="center" class="main">
<table width="300" border="0" cellspacing="0" cellpadding="2" class="main" style="border: 1 solid #000000">
	<tr>
		<td width="300" class="main_bold">
Modify Variables:&nbsp;
<button onclick="window.location='setup.php?variables=yes'" class="formfield">Click Here</button>
<br><br>
Modify Plans:&nbsp;
<button onclick="window.location='setup.php?plans=yes'" class="formfield">Click Here</button>
<br><br>
Setup PayPal Links:&nbsp;
<button onclick="window.location='setup.php?paypal=yes'" class="formfield">Click Here</button>
<br><br>
Setup NOCHEX Links:&nbsp;
<button onclick="window.location='setup.php?nochex=yes'" class="formfield">Click Here</button>
<br><br>
Setup Creditcard Links:&nbsp;
<button onclick="window.location='setup.php?cc=yes'" class="formfield">Click Here</button>
</td>
</tr>
</table>

</td>
</tr>
</table>