<div id="leftdivision">
<table width="130" border="0" cellspacing="0" cellpadding="0" class="maincolor">
<tr>
<td width="130" height="426" align="center" valign="top" class="main_bold">

<br>
<a href="main.php" target="clients" class="menulink">Main</a>

<br>
<br>
<table width="110" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="110" class="main_bold">

<span class="summary_message">Admin CP</span>
<li><a href="staffmanager/addstaff.php" target="clients" class="menulink">Add Staff</a>
<li><a href="email.php" target="clients" class="menulink">Edit Emails</a>
<li><a href="setup.php" target="clients" class="menulink">Setup</a>
<li><a href="statistics.php" target="clients" class="menulink">Statistics</a>
<li><a href="transactions.php" target="clients" class="menulink">Transactions</a>
<li><a href="staffmanager/viewstaff.php" target="clients" class="menulink">View Staff</a>

</td>
</tr>
</table>
<br>
<br>
<table width="110" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="110" class="main_bold">

<span class="summary_message">Client Manager</span>
<li><a href="clientmanager/add.php" target="clients" class="menulink">Add Client</a>
<li><a href="clientmanager/viewclients.php" target="clients" class="menulink">View Client</a>

</td>
</tr>
</table>
<br>
<br>
<table width="110" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="110" class="main_bold">

<span class="summary_message">Support Desk</span>
<li><a href="support/support.php" target="clients" class="menulink">Client Support</a>
<li><a href="clientmanager/message.php" target="clients" class="menulink">Send Message</a>

</td>
</tr>
</table>
</td>
</tr>
</table>
</div>