<div id="leftdivision">
<table width="130" border="0" cellspacing="0" cellpadding="0" class="maincolor">
<tr>
<td width="130" height="426" align="center" valign="top" class="main_bold">

<br>
<table width="110" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="110" class="main_bold">

<span class="summary_message">Support Desk</span>
<li><a href="support/support.php" target="clients" class="menulink">Client Support</a>
<li><a href="clientmanager/message.php" target="clients" class="menulink">Send Message</a>

</td>
</tr>
</table>
</td>
</tr>
</table>
</div>