<br>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td height="35"> 
      <hr noshade width="10%">
      <div align="center">
        <pre><font face="Verdana, Arial, Helvetica, sans-serif" size="1"><a href="http://www.tightprices.com/products/TightAuctions/">TightAuctions</a>&#153; &copy; 2001 <a href="http://www.Tightprices.com">Tightprices</a>.</font></pre>
      </div>
    </td>
  </tr>
</table>
