<div align="center" width="100%">
<table border="0" bordercolor="$_TCFG[_TAG_TABLE_BRDR_COLOR]" cellpadding="0" cellspacing="0" width="100%">
<tr><td valign="top">
<table border="1" bordercolor="$_TCFG[_TAG_TABLE_BRDR_COLOR]" cellpadding="5" cellspacing="1" width="100%">
<tr height="25px"><td valign="top" align="center" colspan="2">
<br>Header Row for whatever<br><br>
</td></tr>
<tr><td valign="top" align="center" width="15%">
Left Column
</td><td valign="top">