<?

 /*
   Copyright (c), 1999, 2000 - phpauction.org
   Copyright (c), 2001, 2002 - webauction.de.vu

   Lizenz siehe lizenz.txt & license

   Die neueste Version kostenfrei zum Download unter:
   http://webauction.de.vu

*/ 



 $durations = array (
                 1  => "1 Tag",
                 7  => "1 Woche",
                 14  => "2 Wochen",
                 21  => "3 Wochen",
                 28 => "4 Wochen"
             );

?>