<?
  
/*
   Copyright (c), 1999, 2000 - phpauction.org
   Copyright (c), 2001, 2002 - webauction.de.vu

   Lizenz siehe lizenz.txt & license

   Die neueste Version kostenfrei zum Download unter:
   http://webauction.de.vu

*/

   $payments = array (
      8      =>      "Vorauskasse",
      1      =>      "Kreditkarte",
      2      =>      "Bargeld",
      3      =>      "Scheck",
      4      =>      "Nachname",
      5      =>      "Überweisung",
      6      =>      "<a target=\"_blank\" href=\"s-itt.php\"><font color=\"#000000\" size=\"2\"
face=\"Arial\">S-ITT</font></a>
",
      7      =>      "Wird in der Beschreibung festgehalten"
   );

?>