<?

  /*
   Copyright (c), 1999, 2000 - phpauction.org
   Copyright (c), 2001, 2002 - webauction.de.vu

   Lizenz siehe lizenz.txt & license

   Die neueste Version kostenfrei zum Download unter:
   http://webauction.de.vu

*/



 $restarts = array (
                 0  => " Keinen Neustart ",
                 1  => " 1 Neustart ",
                 2  => " 2 Neustarts ",
                 3  => " 3 Neustarts ",
                 4  => " 4 Neustarts ",
                 5  => " 5 Neustarts ",
                 6  => " 6 Neustarts ",
                 7  => " 7 Neustarts ",
                 8  => " 8 Neustarts ",
                 9  => " 9 Neustarts ",
                10  => " 10 Neustarts "
             );

?>