ALTER TABLE mytgp_set ADD MAXPERCATEGORY TINYINT (4) DEFAULT '0' not null;
ALTER TABLE mytgp_set ADD MAXPERDOMVIP TINYINT (4) DEFAULT '0' not null;
ALTER TABLE mytgp_set ADD MAXPERMAILVIP TINYINT (4) DEFAULT '0' not null;
ALTER TABLE mytgp_set ADD MAXPERCATEGORYVIP TINYINT (4) DEFAULT '0' not null;
ALTER TABLE mytgp_set ADD CHECKSTATUS VARCHAR (3) not null;
ALTER TABLE mytgp_set ADD CHECKONCLICK VARCHAR (3) not null;
ALTER TABLE mytgp_set ADD CHECKONMOUSE VARCHAR (3) not null;
ALTER TABLE mytgp_post ADD POSTVIP VARCHAR(3) NOT NULL;