<script>window.setTimeout('changeurl();',2000); function changeurl(){window.location='https://auth.paysystems.com/cgi-v310/payment/onlinesale-tpppro.asp?companyid=<?php echo $paysystems_id?>&formget=Y&delivery=N&product1=Shopping%20Basket%20Content&total=<?php echo $total?>&reoccur=N&redirect=<?php echo $paysystems_redirect?>&redirectfail=<?php echo $paysystems_redirect_fail?>&email=<?php echo $email?>'}</script>
<CENTER><FONT FACE="Verdana" SIZE=2 COLOR="<?php echo $TextColor?>">Loading Payment Gateway...</FONT></CENTER>


