CREATE TABLE IPNlog(
sequence BIGINT UNSIGNED NOT NULL AUTO_INCREMENT , 
last_change timestamp( 14 ) NOT NULL , 
txn_type set( 'touched' , 'web_accept' , 'cart' , 'send_money' , 'subscr_signup' , 'subscr_cancel' , 'subscr_failed' , 'subscr_payment' , 'subscr_eot' ) NOT NULL default 'touched' , 
item_number INT NOT NULL UNIQUE , 
item_name varchar( 127 ) NOT NULL default 'UNK' , 
whm_name varchar( 127 ) NOT NULL default 'UNK' , 
coupon_code varchar( 15 ) NOT NULL default 'none' , 
IP varchar( 15 ) NOT NULL default '000.000.000.000' , 
txn_id varchar( 127 ) NOT NULL default '0' , 
parent_txn_id varchar(127 ) default NULL , 
comment varchar( 255 ) default NULL , 
custom varchar( 255 ) default NULL , 
option_name1 varchar( 127 ) NOT NULL default 'Domain Name' , 
option_selection1 varchar( 127 ) NOT NULL default 'UNK' , 
option_name2 varchar( 127 ) NOT NULL default 'User Name' , 
option_selection2 varchar( 127 ) NOT NULL default 'UNK' , 
business varchar(127 ) NOT NULL default 'your_PayPal_account@your-company.net' , 
receiver_email varchar( 127 ) NOT NULL default 'your_PayPal_account@your-company.net' , 
invoice varchar( 127 ) NOT NULL default '0' , 
payment_status set( 'touched' , 'Completed' , 'Pending' , 'Failed' , 'Denied' , 'Refunded' , 'Cancelled' ) NOT NULL default 'touched' , 
pending_reason set( 'echeck' , 'intl' , 'multi_curency' , 'verify' , 'address' , 'upgrade' , 'unilateral' , 'other' , 'N/A' ) NOT NULL default 'N/A' , 
reason_code varchar( 127 ) default NULL , 
payment_date varchar( 127 ) NOT NULL default '0' , 
payment_type set( 'echeck' , 'instant' ) NOT NULL default 'instant' , 
payment_gross varchar( 127 ) NOT NULL default '0' , 
payment_fee varchar(127 ) default '0' , 
mc_gross varchar( 127 ) NOT NULL default '0' , 
mc_fee varchar( 127 ) default '0' , 
mc_currency varchar( 127 ) NOT NULL default 'USD' , 
settle_amount varchar( 127 ) default '0' , 
settle_currency varchar( 127 ) default 'USD' , 
exchange_rate varchar( 127 ) default '0' , 
mc_amount1 varchar( 127 ) default '0' ,  
mc_amount2 varchar( 127 ) default '0' , 
mc_amount3 varchar(127 ) default '0' , 
payer_email varchar( 127 ) default NULL , 
payer_id varchar( 127 ) default NULL , 
payer_status set( 'verified' , 'unverified' , 'intl_verified' ) NOT NULL default 'unverified' , 
first_name varchar( 127 ) default NULL , 
last_name varchar( 127 ) default NULL , 
address_name varchar( 127 ) default NULL , 
address_street varchar( 127 ) default NULL , 
address_city varchar( 127 ) default NULL , 
address_state varchar( 127 ) default NULL , 
address_zip varchar( 127 ) default NULL , 
address_country varchar( 127 ) default NULL , 
address_status set( 'confirmed' , 'unconfirmed' ) NOT NULL default 'unconfirmed' , 
subscr_date varchar( 127 ) NOT NULL default '0' , 
subscr_effective varchar( 127 ) NOT NULL default '0' , 
period1 varchar( 127 ) NOT NULL default 'UNK' , 
period2 varchar( 127 ) NOT NULL default 'UNK' , 
period3 varchar( 127 ) NOT NULL default 'UNK' , 
amount1 varchar( 127 ) NOT NULL default '0' , 
amount2 varchar( 127 ) NOT NULL default '0' , 
amount3 varchar( 127 ) NOT NULL default '0' , 
recurring varchar( 127 ) NOT NULL default '1' , 
reattempt varchar( 127 ) NOT NULL default '1' , 
retry_at varchar( 127 ) default NULL , 
recur_times varchar( 127 ) NOT NULL default '0' , 
username varchar( 127 ) NOT NULL default '0' , 
password varchar( 127 ) NOT NULL default '0' , 
init_pass varchar( 8 ) NOT NULL default 'UNK' , 
subscr_id varchar( 127 ) default NULL , 
verify_sign varchar( 127 ) default NULL , 
notify_version varchar( 127 ) default '1.6' , 
PRIMARY KEY ( item_number ) , 
KEY ( option_selection1 ) , 
KEY ( option_selection2 ) , 
KEY ( sequence ) , 
KEY ( txn_id ) 
) TYPE = MYISAM COMMENT = 'Recieve IPN posts from PayPal servers' 