<?

#################################################################################################
#
#  project           : PHPBazar
#  filename          : header.inc
#  last modified by  : Erich Fuchs
#  supplied by       : Reseting
#  nullified by	     : CyKuH [WTN]
#  purpose           : Header File

#

#################################################################################################



#  Processing Time Start

#################################################################################################

$proctime_start=microtime();



#  HTML Header Start

#################################################################################################

?>



<html>

 <head>

  <title>phpBazar</title>

  <link rel="stylesheet" type="text/css" href="<? echo $STYLE;?>">

  <? echo "$lang_metatag\n"; ?>

  <meta http-equiv="Author" content="NETonE GmbH.">

  <meta name="robots" content="index, follow">

  <meta name="revisit-after" content="20 days">

 </head>



<body>



 <div align="center">

  <table border="0" cellpadding="0" cellspacing="0" width="738" height="67">

   <tr>

    <td width="504">

      <img src="images/pb_banner01.jpg" border=1>

    </td>

    <td width="230">

      <img src="images/pb_logo01.gif" border=1>

    </td>

   </tr>

  </table>

 </div>

