<?

#################################################################################################
#
#  project           	: phpBazar
#  filename          	: spacer.inc
#  last modified by  	: Erich Fuchs
#  supplied by          : Reseting
#  nullified by		: CyKuH [WTN]
#  purpose           	: Space between the tables ....
#
#################################################################################################



echo" <table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"10\" height=4>\n";

echo"   <tr><td>\n";

echo"   </td></tr>\n";

echo" </table>\n";

?>