<script>window.setTimeout('changeurl();',2000); function changeurl(){window.location='https://www.nochex.com/nochex.dll/checkout?email=<?php echo $nochex_email?>&amount=<?php echo $total?>&description=Shopping%20Basket%20Content&logo=<?php echo $nochex_logo?>&returnurl=<?php echo $nochex_returnurl?>&ordernumber=<?php echo $order_id?>'}</script>
<CENTER><FONT FACE="Verdana" SIZE=2 COLOR="<?php echo $TextColor?>">Loading Payment Gateway...</FONT></CENTER>



