<? echo("<?xml version=\"1.0\" encoding=\"".$www_charset."\"?>
<?xml-stylesheet type=\"text/css\" href=\"style.css\" ?>
");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- here you should define DOCTYPE -->
<html>
<head>
<!-- here you can define charset, or you can do it in config file -->
<meta http-equiv="Content-Type" content="text/xml; charset=<?=$www_charset;?>" />
<title><? echo htmlspecialchars($title); ?></title>
<link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body style="background: #CCDDFF;">
<div style="background-color:#FcFcFc;border:1px solid #000000;padding: 5px; text-align: justify;">
