<div id="leftdivision">
<table width="130" border="0" cellspacing="0" cellpadding="0" class="maincolor">
<tr>
<td width="130" height="426" align="center" valign="top" class="main_bold">

<br>
<a href="summary.php" target="clients" class="menulink">Main</a>

<br>
<br>
<table width="110" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="110" class="main_bold">

<span class="summary_message">Account CP</span>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/cron/index.html" target="clients" class="menulink">Cron Jobs</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/mail/email.html" target="clients" class="menulink">Email</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/err/index.html" target="clients" class="menulink">Error Pages</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/ftp/index.html" target="clients" class="menulink">FTP Manager</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/sql/index.html" target="clients" class="menulink">mySQL</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/subdomain/index.html" target="clients" class="menulink">Subdomains</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/submit/index.html" target="clients" class="menulink">Submit Site</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/telnet/index.html" target="clients" class="menulink">Telnet SSH</a>
<li><a href="transactions.php" target="clients" class="menulink">Transactions</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/htaccess/index.html" target="clients" class="menulink">Web Protect</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/stats/webalizer.html" target="clients" class="menulink">Webstats</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/neomail/neomail.pl" target="clients" class="menulink">Webmail</a>
<li><a href="details.php" target="clients" class="menulink">Your Details</a>

</td>
</tr>
</table>
<br>
<br>
<table width="110" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="110" class="main_bold">

<span class="summary_message">Control Panels</span>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>/cpanel/" target="_blank" class="menulink">CPanel 4</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/3rdparty/phpMyAdmin/index.php" target="clients" class="menulink">phpMyAdmin</a>

</td>
</tr>
</table>
<br>
<br>
<table width="110" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="110" class="main_bold">

<span class="summary_message">Support</span>
<li><a href="support.html" target="clients" class="menulink">Index</a>
<li><a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/backup/index.html" target="clients" class="menulink">Backups</a>
<li><a href="http://www.YOURFORUM.COM" target="clients" class="menulink">Forum</a>
<li><a href="support/support.php" target="clients" class="menulink">Helpdesk</a>
<li><a href="http://www.YOURSTATUSPAGE.COM" target="clients" class="menulink">Server Status</a>

</td>
</tr>
</table>
</td>
</tr>
</table>
</div>