<div id="maindivision">
<table width="620" border="0" cellspacing="0" cellpadding="0" class="maincolor">
<tr>
<td width="620" align="center" class="main">
&nbsp;
</td>
</tr>
<tr>
<td width="620" align="center">
<iframe name="clients" frameborder="0" src="summary.php" width="610" height="400"></iframe>
</td>
</tr>
<tr>
<td width="620" align="center" class="main">
Copyright © 2001 - 2002
<a href="http://www.phpmanager.com" class="copyrightlink" target="_blank">phpManager</a>
, All Rights Reserved
</td>
</tr>
</table>
</div>