<script language="JavaScript">

<!-- Cloak Engaged

//MSIE 4.x Detection

  if ((navigator.appName == "Microsoft Internet Explorer") && (parseInt(navigator.appVersion) >= 4 ))

     {}

  else

     {alert("These pages are optimised for MS Internet Explorer 4.0 and higher, and for display resolutions of 800x600 pixels! You're using another browser and therefore it is possible that the pages will not display correctly!!!");}

//-- Cloak Disengaged -->

</script>



