<br>

Welcome to <em id="red">phpBazar</em>!!! The ultimate classified ad & matchmaking Software.<br>

<br>

This DEMObazar is FULL equipped with all option's availiable:<br>

<br>

<li> phpBazar

<li> phpBazarPicLib

<li> phpBazarSales

<li> phpBazarChat

<li> phpBB V2.0 Forum (FREE)

<li> ImageMagick's Picture "convert" (FREE)

<br>

<br>

Feel free to surf around and check out the functions ... <br>

<br>

Your SmartISoft-Team<br>

<br>

<br>

<center><a href="classified.php?choice=top">TOP ADS</a></center>