<div class="mainheader">Thank You<p><div>

<div class="maintext">

<br>

You have been registered (still pending). <br>

We have sent an email to <b><? echo "$email";?></b><br>

<br>

<br>

To complete your registration you will need to check your email and then click on the URL sent to confirm your account. You will then be able to Login with your Username and Password.<BR><BR> If you do not complete registration within 48 hours your account will be purged.<br><br><center><form action=javascript:window.close() METHOD=POST><input type=submit value=Done></form></center></div>