<div class="mainheader">Welcome</div>

<div class="maintext">

<br>

Welcome to phpBazar!<br>

<br>

This is the welcome screen for your site !!!<br><br>

If you have adult content on your domain you should do an age-check ...<br><br>

This Site may contain adult Content!! You must be aged 18 or over to enter this Site !!!

If not please leave !!!<br>

<br>

Thank you.<br>

<br>

<center>

<a href="http://www.disney.com">NO, I'm NOT over 18 Years</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<a href="main.php">Yes I'm over 18 Years</a>

</center>

</div>