<?

// English language file for Best Top List
// Copyright 2002 - Szymon Kosok



$lang['addasite'] = "Add a site";
$lang['error_forgot'] = "You forgot something. :-) Please correct this!";
$lang['error_db_hou'] = "Hmmm... Houston, we have a problem ... please wait 5 minutes and try again... if error still appear, please contact admin: " . $option['adminmail'];
$lang['mail_title1'] = "Your site has been added to " . $option['nameoflist'] . "!";
$lang['mail_body1'] = "Hello!\n\nYour site has been added to the " . $option['nameoflist'] . " and waiting for administator authorization.\n\nThis is HTML code:\n\n<a href=http://" . $option['siteurl'] . "/in.php?id=";
$lang['mail_body2'] = "><img src=http://" . $option['siteurl'] . "/images/button.jpg border=0></a>.\n\nIf you wanna edit your information go to - http://" . $option['siteurl'] . "/edit.php\n\nIf you lost password point browser to - http://" . $option['siteurl'] . "/lostpass.php\n\nIf you have any problems contact admin: " . $option['adminmail'] . ".\n\nGreetings,\n\n" . $option['nameoflist'] . " Team.\n\n_____________\n\nGenerated by Best Top List by Szymon Kosok - http://www.best-scripts.tk";
$lang['site_added1'] = "Site added! Thx! :)<br><br>Now ... Paste this code in visible place on your site<br>In 24 h top list administrator authorize your site... <br><br>HTML code:<br><br><b> &lt;a href=http://" . $option['siteurl'] . "/in.php?id=";
$lang['site_added2'] = ">&lt;img src=http://" . $option['siteurl'] . "/images/button.jpg border=0>&lt;/a>";
$lang['sitename'] = "Name of site";
$lang['description'] = "Description";
$lang['bannerurl'] = "Banner URL";
$lang['yourmail'] = "Your e-mail";
$lang['siteurl'] = "Site URL";
$lang['password'] = "Password";
$lang['submit'] = "Submit";
$lang['uploadtxt'] = "This is the place where you can upload your bannner to our server.";
$lang['siteurlwohttp'] = "Site URL (without http://)";
$lang['baduser'] = "Bad username!";
$lang['url'] = "URL";
$lang['badpass'] = "Bad password!";
$lang['editdone'] = "Information has been updated :-)<br><br><a href=index.php>Back to index</a>";
$lang['addsite'] = "Add your site";
$lang['editsite'] = "Edit your site";
$lang['lp'] = "Lost password";
$lang['contact'] = "Contact";
$lang['taf'] = "Tell a friend";
$lang['rules'] = "Rules";
$lang['lostcode'] = "Lost HTML code";
$lang['bannerhosting'] = "Your banner on our server";
$lang['news'] = "News";
$lang['home'] = "Home";
$lang['search'] = "Search";
$lang['aboutproject'] = "About Project";
$lang['ifyouwanna'] = "If you wanna vote for this site in " . $option['nameoflist'] . " click here";
$lang['recommended'] = "Recommended";
$lang['rank'] = "Rank";
$lang['site'] = "Site";
$lang['in'] = "In";
$lang['out'] = "Out";
$lang['totalsites'] = "Total sites";
$lang['sitesauth'] = "Sites waiting for authorization";
$lang['nosite'] = "We dont have this site on our database";
$lang['yourhtml'] = "Your HTML Code";
$lang['dontspam'] = "Please dont spam";

// !!! change in 2.07. !!!

$lang['lpmail'] = "Hello,\n\nYour new password: ";
$lang['lpmail2'] = ".\n\nRegards,\n\nTeam " . $option['nameoflist'] . "";

// eoc

$lang['lpmailed'] = "Password has been sent to the registered e-mail";
$lang['posted'] = "posted by";
$lang['aboutprojecttxt'] = "<center><b>Top List by Nookie v. 1.01.</b>
<br><br>Author: Szymon 'Nookie' Kosok
<br>Original graphics: Ashlee
<br><br>Thx:
<br>Ashlee for graphics and for all support.
<br>Robin for server with PHP & MySQL. :)
<br>PHP for great programming language
<br>MySQL for great database :-)
<br><br>TO DO:<br><br>
</center>Please visit http://www.best-sripts.tk for news, new releases etc. :)";
$lang['searchresults'] = "Search results";
$lang['antispam'] = "Sorry, you can send only one invite per 3 h! This is anti-spam filter!";
$lang['tfym'] = "Your mail";
$lang['tffm'] = "Friend mail";
$lang['invite'] = "Invite";
$lang['tfymtxt'] = "Hello!\n\nYour friend ($mail1) invite you to add your site to " . $option['nameoflist'] . " top list. If you are interesed visit http://" . $option['siteurl'] . ".\n\nRegards,\nTeam $nameoflist\n\n_____________\n\nGenerated by Best Top List by Szymon Kosok - http://www.best-scripts.tk";
$lang['tf'] = "Tell a friend";
$lang['tfyms'] = "Thx! Mail sent.";
$lang['doesntcount'] = "Vote doesn't counted!<br><br><a href=index.php>Click here to view top list without voting</a>";
$lang['cheater'] = "Cheater! Please remove voting gate!";
$lang['indesc'] = "in description";
$lang['intitle'] = "in title";
$lang['viewstats'] = "View stats";

// added in 1.12.

$lang['notyet'] = "Not yet rated...";
$lang['rating'] = "Rating";
$lang['votes'] = "Votes";
$lang['sortby'] = "Sort by";
$lang['rateit'] = "Rate this site!";
$lang['norate'] = "No, thx, I dont want";

// added in 1.13

$lang['nosite'] = "There is no site with this id in our database!";

// added in 1.14

$lang['mail_bodyacc1'] = "Hello!\n\nYour site has been added to the " . $option['nameoflist'] . ".\n\nThis is HTML code:\n\n<a href=http://" . $option['siteurl'] . "/in.php?id=";
$lang['mail_bodyacc2'] = "><img src=http://" . $option['siteurl'] . "/images/button.jpg border=0></a>.\n\nIf you wanna edit your information go to - http://" . $option['siteurl'] . "/edit.php\n\nIf you lost password point browser to - http://" . $option['siteurl'] . "/lostpass.php\n\nIf you have any problems contact admin: " . $option['adminmail'] . ".\n\nGreetings,\n\n" . $option['nameoflist'] . " Team.\n\n_____________\n\nGenerated by Best Top List by Szymon Kosok - http://www.best-scripts.tk";
$lang['site_addedacc1'] = "Site added! Thx! :)<br><br>Now ... Paste this code in visible place on your site<br>... <br><br>HTML code:<br><br><b> &lt;a href=http://" . $option['siteurl'] . "/in.php?id=";
$lang['site_addedacc2'] = ">&lt;img src=http://" . $option['siteurl'] . "/images/button.jpg border=0>&lt;/a>";

// added in 1.16.

$lang['alltimein'] = "All time IN";
$lang['alltimeout'] = "All time OUT";
$lang['notifsub'] = "Site added to your Top List - " . $option['nameoflist'];
$lang['notifbody'] = "Site added: \n\nName: " . $nazwa . "\nURL: " . $url . "\nDescription: " . $opis . "\nBanner: " . $banner . "\n\nIf you have disabled auto-accept feature please renember to accept this site (or not)";

// added in 1.18 GOLD

$lang['bannerbig'] = "Banner is too big!";

// added in 2.02

$lang['nsr'] = "Next site reset";
$lang['comments'] = "Comments";

// added in 2.03

$lang['bookmark'] = "Add this toplist to bookmarks";
$lang['homepage'] = "Set as your home page";

// added in 2.04

$lang['user'] = "Username";
$lang['userexist'] = "Sorry, there is user with the same name in our database!";

// Added in 2.06

$lang['postacomment'] = "Post a comment";
$lang['nocomments'] = "There is no comments for this site";
$lang['posted'] = "posted";
$lang['nick'] = "Nick";
$lang['comment'] = "Comment";
$lang['rate'] = "Rate!";
$lang['backto'] = "Back to";
$lang['woframes'] = "View this site without this frame";

// added in 2.07

$lang['actualin'] = "Actual IN";
$lang['actualout'] = "Actual OUT";
$lang['alltimein'] = "All time IN";
$lang['alltimeout'] = "All time OUT";
$lang['outstats'] = "OUT stats (last $recordsout)";
$lang['instats'] = "IN stats (last $recordsin)";
$lang['records'] = "Show ";
$lang['records1'] = " IN records and ";
$lang['records2'] = " OUT records";
$lang['newpass'] = "New password (leave blank if you dont want change)";
$lang['newpassr'] = "New password again";
$lang['passmatch'] = "Passwords doesn't match!";
$lang['category'] = "Category";
$lang['choosecat'] = "Choose category";

// added in 2.09.

$lang['globalstats'] = "Global stats (all categories)";

// Upload messages

$message["fileisbig"] = "Too big file! ("

                        . $filesize_limit . "kB)";

$message["invext"] = "Bad extension!.";
$message["incomplete"] = "Upload isn\'t completed.";
$message["complete"] = "Upload completed!.";
$message["uploadbutton"] = "Upload";
$message["uploadtxt"] = "Banner: ";
$message["fileexists"] = "There is banner on our server with the same name! :)";
