<?php

$access_denied = "Accédez nié";

$activationemail_password = "Votre mot de passe choisi";
$activationemail_sent = "Email d'activation envoyé";

$add = "Ajoutent";

$back = "Dos";

$date = "Date:";
$details = "Détails:";
$domainmsg = "Domaine:";

$user_taken = "L'erreur, username a été déjà prise. Veuillez choisir autre.";

$client_activated = "Le Client A été lancé.";
$client_added = "Le Client A été ajouté.";
$client_cancelled = "Client Annulé.";
$client_confdel = "Êtes vous sûr vous voulez effacer ce client?";
$client_deleted = "Le client a été effacé.";
$client_duedate = "Date due de paiement pour le client ID:";
$client_edited = "Enregistrez Édité.";
$client_email = "Tous les clients ont été emailed.";
$client_emailsent = "Un email a été envoyé à";
$client_error = "Erreur, incapable de rechercher des petits groupes de client .";
$client_id = "Client ID:";
$client_modifypass = "Mot de passe Édité.";
$client_noinvoice = "Aucun client à facturer";
$client_nopending = "Aucun client en suspens";
$client_notactivated = "Client Non lancé. Veuillez compléter toutes les requises zones.";
$client_notadded = "Client Non ajouté. Veuillez compléter toutes les requises zones.";
$client_notfound = "Client ID non trouvé.";
$client_nopending = "Il n'y a aucun client en suspens à lancer.";
$client_unpaid = "Aucun client toujours à payer";
$client_updated = "Des Enregistrements De Client Ont été mis à jour.";
$client_updatedmsg = "Vos détails de contact ont été mis à jour.";

$company_biannual = "Nombre total bisannuels des clients:";
$company_biannualincome = "Revenu total bisannuels des clients:";
$company_clients = "Nombre total des clients:";
$company_monthly = "Nombre total mensuels des clients:";
$company_monthlyincome = "Revenu total mensuels des clients:";
$company_quarterly = "Nombre total trimestriels des clients:";
$company_quarterlyincome = "Revenu total trimestriels des clients:";
$company_statistics = "Statistiques De Compagnie";
$company_totalincome = "Total annuel revenu:";
$company_yearly = "Nombre total annuels des clients:";
$company_yearlyincome = "Revenu total annuels des clients:";

$dealtby = "Occupé Par:";

$descriptionmsg = "Description:";

$domain_notfound = "Domaine non trouvé.";

$duedatemsg = "Date Due De Paiement:";

$edit = "Éditent";

$email_activation = "L'email de lancement de compte a été modifié.";
$email_adminamend = "Les Admin modifient l'email de support ont été modifiés.";
$email_cancellation = "L'email d'annulation de compte a été modifié.";
$email_chequeconfirmation = "L'email de confirmation de chèque a été modifié.";
$email_clientamend = "Le client modifient l'email de support a été modifié.";
$email_closesupport = "L'email étroit de support a été modifié.";
$email_ccconfirmation = "L'email de confirmation de carte de crédit a été modifié.";
$email_invoice = "L'email de facture a été modifié.";
$email_moniesconfirmation = "L'email de confirmation d'argents a été modifié.";
$emailmsg = "Email:";
$email_neworder = "Le nouvel email de commande a été modifié.";
$email_nochexconfirmation = "L'email de confirmation de NOCHEX a été modifié.";
$email_ordercancellation = "L'email d'annulation de commande a été modifié.";
$email_paypalconfirmation = "L'email de confirmation de PayPal a été modifié.";
$email_receipt = "L'email de réception a été modifié.";
$email_submitted = "Vous email a été soumis. Nous répondrons à votre email aussitôt que possible.";
$email_support = "Le nouvel email de support a été modifié.";
$email_supportnotice = "L'email de notification de support a été modifié.";

$fillfields = "Veuillez compléter toutes les requises zones.";

$invoice_amount = "Quantité Due:";
$invoice_amountreceived = "La Quantité A reçu:";
$invoice_changedate = "Date de facture pour Client ID:";
$invoice_changed = "a été changé.";
$invoice_date = "Date De Facture:";
$invoice_duedate = "Date Due De Paiement:";
$invoice_message = "L'exposition ci-dessous est un sommaire de votre facture. Une copie a également été emailed à vous. Veuillez effectuer votre paiement d'ici la date due de paiement autrement que nous pouvons, à notre discrétion unique, suspendre votre compte jusqu'à ce que tous les argents dus soient aient effacé. Si vous payez par PayPal ou carte de crédit, vous n'avez pas besoin de prendre toute autre mesure.";
$invoice_method = "Méthode De Paiement:";
$invoice_notification = "Avis De Facture";
$invoice_query = "Si vous avez n'importe quelles requêtes, ou ne pouvez pas payer cette facture, svp contactez-nous en envoyant une demande de support aussitôt que possible.";
$invoice_receipt = "Réception De Client";
$invoice_receiptmsg = "Cette réception doit reconnaître que votre paiement a été reçu. Une copie a également été emailed à vous.";
$invoice_regards = "Respects,";
$invoice_schedule = "Échéancier de remboursement:";
$invoice_sent = "Facture de client envoyée.";
$invoice_thankyou = "Merci de vos affaires,";

$links_ccmodified = "Liens De Carte de crédit Modifiés";
$links_nochexmodified = "Liens De Nochex Modifiés";
$links_paypalmodified = "Liens De PayPal Modifiés";

$login_error = "Erreur: Vous avez écrit une combinaison fausse d'Username/Password.";
$login_pass = "Veuillez entrer votre mot de passe.";
$login_thankyou = "Merci d'entrer";
$login_user = "Veuillez écrire votre username.";
$login_userpass = "Veuillez entrer votre username et mot de passe.";

$newduedate = "Écrivez La Date Due De Nouveau Paiement";
$newinvoicedate = "Écrivez La Nouvelle Date De Facture";
$newticket = "Nouveau Billet";

$no = "Aucun";

$notransactions = "Il n'y a aucune transaction sur cette date.";
$notransactionsmsg = "Vous n'avez aucune transaction.";

$packagemsg = "Module:";

$plan_added = "Plan Ajouté";
$plan_deleted = "Plan Effacé";
$plan_modified = "Plan Modifié";
$plan_name = "Veuillez écrire le nom de plan";

$search = "Recherche";

$searchtransactiondate = "Recherche à Date:";

$showallmsg = "Montrez Tout";

$staff_added = "Membre De Personnel Ajouté.";
$staff_deleted = "Le membre de personnel a été effacé.";
$staff_edited = "Membre De Personnel Édité.";
$staff_error = " Erreur, incapable de rechercher des petits groupes de personnel .";
$staff_modifypass = "Mot de passe Édité.";
$staff_notadded ="Membre De Personnel Non ajouté. Veuillez compléter toutes les requises zones.";
$staff_notfound = "Identification de personnel non trouvée.";

$statusmsg = "Mode:";

$subjectmsg = "Sujet:";

$support_assigned = "Demandes Assignées De Support";
$support_close = "Étroit Billet";
$support_closed = "Demande de support fermée.";
$support_closedmsg = "Cette demande de support a été fermée.";
$support_description = "Ajoutez à la description";
$support_email = "Un email a été également envoyé fournie à l'adresse.";
$support_enter = "Veuillez écrire votre ajout à la demande de support.";
$support_error = "Erreur, incapable de trouver le nombre de billet. S'il vous plaît resaisissez.";
$support_fields = "Veuillez compléter toutes les requises zones.";
$support_modified = "La demande de support a été modifiée.";
$support_new = "Nouvelles Demandes De Support";
$support_noassigned = "Aucune demande assignée de support";
$support_nonew = "Aucune nouvelle demande de support";
$support_received = " Votre demande de support a été reçue aussitôt que possible et sera assignée à un membre de notre équipe de support.";
$support_regards = "Respects,";
$support_resolved = "Votre demande de support a été résolue. Merci pour l'usage de notre système de billet de support .";
$support_submit = "Merci de soumettre votre demande de support. Votre nombre de billet est:";
$support_team = "Équipe De Support";
$support_thankyou = "Merci pour l'usage de notre système de billet de support";

$time = "Temps:";

$ticketnumber = "Nombre De Billet:";

$update = "Mise à jour";
$usernamemsg = "Username:";
$username_notfound = "Username non trouvé.";

$variables_modified = "Variables Modifiées";

$viewticket = "Billet De Vue";

$webaddress = "URL:";

$yes = "Oui";

?>