<?php

$access_denied = "Zugang verweigert";

$activationemail_password = "Ihr gewähltes Kennwort";
$activationemail_sent = "Aktivierung email sendete";

$add = "Hinzufügen";

$back = "Zurück";

$date = "Datum:";
$details = "Details:";
$domainmsg = "Domain:";

$user_taken = "Fehler, username ist bereits in Benutzung. Wählen Sie bitte einen anderen.";

$client_activated = "Kunde wurde aktiviert.";
$client_added = "Kunde wurde hinzugefügt.";
$client_cancelled = "Kunde geschlossen.";
$client_confdel = "Sind Sie sicher dass Sie diesen Kunden löschen möchten?";
$client_deleted = "Kunde wurde gelöscht.";
$client_duedate = "Zahlungfrist für Kundennummer:";
$client_edited = "Aenderungen gespeichert";
$client_email = "Email wurde alle Kunden versand.";
$client_emailsent = "Eine Email wurde gesendet an";
$client_error = "Fehler, nicht imstande Kundendetails abzurufen.";
$client_id = "Kundennummer:";
$client_modifypass = "Passwort geaendert.";
$client_noinvoice = "Keine Kunden mit offenen Rechnungen";
$client_nopending = "Keine zuaktivierende Kunden";
$client_notactivated = "Kunde nicht aktiviert. Füllen Sie bitte alle benötigten Felder aus.";
$client_notadded = "Kunde nicht hinzugefügt. Füllen Sie bitte alle benötigten Felder aus.";
$client_notfound = "Kundennummer nicht gefunden.";
$client_nopending = "Es gibt keine zu aktivierenden Kunden";
$client_unpaid = "Keine nichtbezahlten Rechnungen";
$client_updated = "Kundensätze wurden aktualisiert.";
$client_updatedmsg = "Ihre Kontaktdetails sind aktualisiert worden.";

$company_biannual = "Gesamtzahl der halbjahres Kunden:";
$company_biannualincome = "Gesamteinkommen von den halbjahres Kunden:";
$company_clients = "Gesamtzahl der Kunden:";
$company_monthly = "Gesamtzahl der Monatskunden:";
$company_monthlyincome = "Gesamteinkommen von den Monatskunden:";
$company_quarterly = "Gesamtzahl der vierteljährlichen Kunden:";
$company_quarterlyincome = "Gesamteinkommen von den vierteljährlichen Kunden:";
$company_statistics = "Firmenstatistik";
$company_totalincome = "Totaljahreseinkommen:";
$company_yearly = "Gesamtzahl der jährlichen Kunden:";
$company_yearlyincome = "Gesamteinkommen von den jährlichen Kunden:";

$dealtby = "berabeitet von:";

$descriptionmsg = "Beschreibung:";

$domain_notfound = "Domain nicht gefunden.";

$duedatemsg = "Zahlungfrist:";

$edit = "Bearbeiten";

$email_activation = "Kontoaktivierung Email wurde geändert.";
$email_adminamend = "Adminsupport Email wurde geändert.";
$email_cancellation = "Kontoannullierungemail wurde geändert.";
$email_chequeconfirmation = "Scheckbestätigungsemail wurde geändert.";
$email_clientamend = "Kundensupportemail wurde geändert.";
$email_closesupport = "Supportschliessungsemail wurde geändert.";
$email_ccconfirmation = "Kreditkartebestätigungsemail wurde geändert.";
$email_invoice = "Rechnungsemail wurde geändert.";
$email_moniesconfirmation = "Geldbestätigungsemail wurde geändert.";
$emailmsg = "Email:";
$email_neworder = "Neubestellungsemail wurde geändert.";
$email_nochexconfirmation = "NOCHEX-Bestätigungsemail wurde geändert.";
$email_ordercancellation = "Bestllungsannullierungsemail wurde geändert.";
$email_paypalconfirmation = "PayPalbestätigungsemail wurde geändert.";
$email_receipt = "Empfangsemail wurde geändert.";
$email_submitted = "Ihre Email wurde erfolgreich gesendet. Wir werden auf Ihre Email so bald wie möglich antworten.";
$email_support = "Neue Supportemail wurde geändert.";
$email_supportnotice = "Supportnotizemail wurde geändert.";

$fillfields = "Füllen Sie bitte alle benötigten Felder aus.";

$invoice_amount = "Rechnungsbetrag:";
$invoice_amountreceived = "Rechnungsbetrag empfangen:";
$invoice_changedate = "Rechnungsdatum für Kundennummer:";
$invoice_changed = "wurde geändert.";
$invoice_date = "Rechnungsdatum:";
$invoice_duedate = "Zahlungsfrist:";
$invoice_message = "Folgend ist eine Zusammenfassung Ihrer Rechnung aufgelistet. Ein Kopie wurde Ihnen auch per Email geschickt. Zahlen sie bitte im Rahmen der Zahlungsfrist. Bei Ueberschreitung der Zahlungsfrist sind wir gezwungen Ihr Benutzerkonto vorrbergehend zu schliessen bis Sie alle austehenden Zahlungen beglichen haben. Wenn Sie per PayPal oder Kreditkarte zahlen, brauchen Sie keine weiteren Maßnahmen zu ergreifen.";
$invoice_method = "Zahlungsmethode:";
$invoice_notification = "Rechnungsmitteilung";
$invoice_query = "Wenn Sie irgendwelche Fragen haben oder aus sonstigen Gruenden nicht imstande/bereit sind, diese Rechnung zu bezahlen, treten Sie bitte mit uns so schnell wie möglich in Verbindung!";
$invoice_receipt = "Kundenquittung";
$invoice_receiptmsg = "Dieser Nachricht bestätigt, daß Ihre Zahlung empfangen wurden. Ein Kopie dieser Nachricht wurde auch an die von Ihnen angegebene Emailadresse geschickt.";
$invoice_regards = "MfG,";
$invoice_schedule = "Zahlungsliste:";
$invoice_sent = "Kunderechnung gesendet.";
$invoice_thankyou = "";

$links_ccmodified = "Kreditkartenlinks geändert";
$links_nochexmodified = "Nochexlinks geändert";
$links_paypalmodified = "PayPallinks geändert";

$login_error = "Fehler: Sie haben einen falschen Benutzernamen oder falsches Passwort eigegeben.";
$login_pass = "Tragen Sie bitte Ihr Passwort ein.";
$login_thankyou = "Willkommen";
$login_user = "Tragen Sie bitte Ihren Benutzernamen ein.";
$login_userpass = "Bitte tragen Sie Ihren Benutzernamen und Passwort ein.";

$newduedate = "Neue Zahlungfrist eintragen";
$newinvoicedate = "Neues Rechnungsdatum eingeben";
$newticket = "Neue Anfrage";

$no = "Nein";

$notransactions = "Es gibt keine Transaktionen fuer dieses Datum.";
$notransactionsmsg = "Keine Transaktionen vorhanden.";

$packagemsg = "Paket:";

$plan_added = "Plan hinzugefügt";
$plan_deleted = "Plan gelöscht";
$plan_modified = "Plan geändert";
$plan_name = "Tragen Sie bitte den Paketnamen ein";

$search = "Suchen";

$searchtransactiondate = "Suchen nach Datum:";

$showallmsg = "Alles anzeigen";

$staff_added = "Personal hinzgefügt.";
$staff_deleted = "Personal wurde gelöscht.";
$staff_edited = "Personaldaten bearbeitet.";
$staff_error = "Fehler, nicht imstande Personaldaten zu bearbeiten.";
$staff_modifypass = "Passwort bearbeitet.";
$staff_notadded =" Personal nicht hinzugefügt. Füllen Sie bitte alle benötigten Felder aus.";
$staff_notfound = "Personal ID nicht gefunden.";

$statusmsg = "Status:";                 

$subjectmsg = "Thema:";

$support_assigned = "Zugewiesene Supportanfragen";
$support_close = "Supportanfrage schliessen";
$support_closed = "Supportanfrage geschlossen.";
$support_closedmsg = "Diese Supportanfrage wurde geschlossen.";
$support_description = "Zur Beschreibung hinzufügen";
$support_email = "Eine Besttugunsemail wurde zu der von Ihnen angegebenen Emailadresse geschickt.";
$support_enter = "Tragen Sie bitte Ihre zusaetzlichen Angaben zur Supportanfrage ein.";
$support_error = "Fehler, nicht imstande Supportanfragennummer zu finden. Bitte verscuhen sie es erneut.";
$support_fields = "Füllen Sie bitte alle benoetigten Felder aus.";
$support_modified = "Die Supportanfrage wurde geändert.";
$support_new = "Neue Supportanfragen";
$support_noassigned = "Keine zugewiesenen Supportanfragen";
$support_nonew = "Keine neuen Supportanfragen";
$support_received = "Ihre Supportanfrage wurde empfangen und wird so bald wie moeglich bearbeitet.";
$support_regards = "MfG,";
$support_resolved = "Ihr Supportanfrage ist wurde beantwortet.";
$support_submit = "Ihre Supportanfragennummer ist:";
$support_team = "SupportTeam";
$support_thankyou = "";

$time = "Zeit:";

$ticketnumber = "Supportanfragennummer:";

$update = "Aktualisieren";
$usernamemsg = "Benutzername:";
$username_notfound = "Benutzername nicht gefunden.";

$variables_modified = "Variablen geaendert";

$viewticket = "Anfrage ansehen";

$webaddress = "URL:";

$yes = "Ja";

?>
