<?php

$access_denied = "Accedere a negato";

$activationemail_password = "La vostra parola d'accesso scelta";
$activationemail_sent = "Il email di attivazione ha trasmesso";

$add = "Aggiungono";

$back = "Parte posteriore";

$date = "Data:";
$details = "Particolari:";
$domainmsg = "Settore:";

$user_taken = "L' errore, username già è stato preso. Scegliere prego un altro.";

$client_activated = "Il Cliente È stato attivato.";
$client_added = "Il Cliente È stato aggiunto.";
$client_cancelled = "Cliente Annullato.";
$client_confdel = "Siete sicuri voi desiderate cancellare questo cliente?";
$client_deleted = "Il cliente è stato cancellato.";
$client_duedate = "Data dovuta di pagamento per il cliente ID:";
$client_edited = "Registrare Stampato.";
$client_email = "Tutti i clienti sono stati emailed.";
$client_emailsent = "Un email è stato trasmesso a";
$client_error = "Errore, incapace richiamare i particolari del cliente.";
$client_id = "Cliente ID:";
$client_modifypass = "Parola d'accesso Stampato.";
$client_noinvoice = "Nessun clienti da fatturare";
$client_nopending = "Nessun clienti in corso";
$client_notactivated = "Cliente Non attivato. Riempire prego tutti i richiesti campi.";
$client_notadded = "Cliente Non aggiunto. Riempire prego tutti i richiesti campi.";
$client_notfound = "Identificazione del cliente non trovato.";
$client_nopending = "Non ci sono clienti in corso da attivare.";
$client_unpaid = "Nessun clienti ancora da pagare";
$client_updated = "I Record Del Cliente Sono stati aggiornati.";
$client_updatedmsg = "I vostri particolari del contatto sono stati aggiornati.";

$company_biannual = "Numero totale biennali di clienti:";
$company_biannualincome = "Reddito totale biennali dai clienti:";
$company_clients = "Numero totale di clienti:";
$company_monthly = "Numero totale mensili di clienti:";
$company_monthlyincome = "Reddito totale mensili dai clienti:";
$company_quarterly = "Numero totale trimestrali di clienti:";
$company_quarterlyincome = "Reddito totale trimestrali dai clienti:";
$company_statistics = "Statistiche Dell' Azienda";
$company_totalincome = "Totale annuale reddito:";
$company_yearly = "Numero totale annuali di clienti:";
$company_yearlyincome = "Reddito totale annuali dai clienti:";

$dealtby = "Trattato Da:";

$descriptionmsg = "Descrizione:";

$domain_notfound = "Settore non trovato.";

$duedatemsg = "Data Dovuta Di Pagamento:";

$edit = "Stampano";

$email_activation = "Il email di attivazione di cliente è stato modificato.";
$email_adminamend = "I Admin emendano il email di sostegno sono stati modificati.";
$email_cancellation = "Il email di annullamento di cliente è stato modificato.";
$email_chequeconfirmation = "Il email di conferma dell' assegno è stato modificato.";
$email_clientamend = "Il cliente emenda il email di sostegno è stato modificato.";
$email_closesupport = "Il email vicino di sostegno è stato modificato.";
$email_ccconfirmation = "Il email di conferma della carta di credito è stato modificato.";
$email_invoice = "Il email della fattura è stato modificato.";
$email_moniesconfirmation = "Il email di conferma dei soldi è stato modificato.";
$emailmsg = "Email:";
$email_neworder = "Il nuovo email di ordine è stato modificato.";
$email_nochexconfirmation = "Il email di conferma di NOCHEX è stato modificato.";
$email_ordercancellation = "Il email di annullamento di ordine è stato modificato.";
$email_paypalconfirmation = "Il email di conferma di PayPal è stato modificato.";
$email_receipt = "Il email della ricevuta è stato modificato.";
$email_submitted = "Email siete stati presentati. Risponderemo al vostro email appena possibile.";
$email_support = "Il nuovo email di sostegno è stato modificato.";
$email_supportnotice = "Il email dell' avviso di sostegno è stato modificato.";

$fillfields = "Riempire prego tutti i richiesti campi.";

$invoice_amount = "Importo Dovuto:";
$invoice_amountreceived = "Importo Ricevuto:";
$invoice_changedate = "Data della fattura per il cliente ID:";
$invoice_changed = "è stato cambiato.";
$invoice_date = "Data Della Fattura:";
$invoice_duedate = "Data Dovuta Di Pagamento:";
$invoice_message = "L' esposizione sotto è un sommario della vostra fattura. Una copia egualmente è stata emailed a voi. Effettuare prego il vostro pagamento entro la data dovuta di pagamento possiamo, alla nostra sola discrezione, sospendere al contrario che il vostro cliente fino a che tutti i soldi dovuti non siano abbiano annullato. Se state pagando da PayPal o dalla carta di credito, non dovete intraprendere nuova azione.";
$invoice_method = "Metodo Di Pagamento:";
$invoice_notification = "Notifica Della Fattura";
$invoice_query = "Se avete qualunque domande, o non potete pagare questa fattura, metterseli in contatto con prego trasmettendo una richiesta di sostegno appena possibile.";
$invoice_receipt = "Ricevuta Del Cliente";
$invoice_receiptmsg = "Questa ricevuta deve riconoscere che il vostro pagamento è stato ricevuto. Una copia egualmente è stata emailed a voi.";
$invoice_regards = "Riguardi,";
$invoice_schedule = "Programma Di Pagamento:";
$invoice_sent = "La fattura del cliente ha trasmesso.";
$invoice_thankyou = "Grazie per il vostro commercio,";

$links_ccmodified = "Collegamenti Della Carta di credito Modificato";
$links_nochexmodified = "Collegamenti Di Nochex Modificato";
$links_paypalmodified = "Collegamenti Di PayPal Modificato";

$login_error = "Errore: Avete entrato in una combinazione errata di Username/Password.";
$login_pass = "Digitare prego la vostra parola d'accesso.";
$login_thankyou = "Grazie per entrare";
$login_user = "Entrare prego nel vostro username.";
$login_userpass = "Digitare prego il vostri username e parola d'accesso.";

$newduedate = "Entrare Nella Data Dovuta Di Nuovo Pagamento";
$newinvoicedate = "Entrare Nella Nuova Data Della Fattura";
$newticket = "Nuovo Biglietto";

$no = "Nessun";

$notransactions = "Non ci sono transazioni su quella data.";
$notransactionsmsg = "Non avete alcune transazioni.";

$packagemsg = "Pacchetto:";

$plan_added = "Programma Aggiunto";
$plan_deleted = "Programma Cancellato";
$plan_modified = "Programma Modificato";
$plan_name = "Digitare prego il nome di programma";

$search = "Ricerca";

$searchtransactiondate = "Ricerca entro Date:";

$showallmsg = "Mostrare Tutto";

$staff_added = "Membro Del Personale Aggiunto.";
$staff_deleted = "Il membro del personale è stato cancellato.";
$staff_edited = "Membro Del Personale Stampato.";
$staff_error = "Errore, incapace richiamare i particolari del personale.";
$staff_modifypass = "Parola d'accesso Stampato.";
$staff_notadded ="Membro Del Personale Non aggiunto. Riempire prego tutti i richiesti campi.";
$staff_notfound = "Identificazione del personale non trovato.";

$statusmsg = "Condizione:";

$subjectmsg = "Oggetto:";

$support_assigned = "Richieste Assegnate Di Sostegno";
$support_close = "Vicino Biglietto";
$support_closed = "Richiesta di sostegno chiuso.";
$support_closedmsg = "Questa richiesta di sostegno è stata chiusa.";
$support_description = "Aggiungere alla descrizione";
$support_email = "Un email egualmente è stato trasmesso fornito all' indirizzo.";
$support_enter = "Fornire prego la vostra aggiunta alla richiesta di sostegno.";
$support_error = "Errore, incapace trovare numero del biglietto. Prego re-enter.";
$support_fields = "Riempire prego tutti i richiesti campi.";
$support_modified = "La richiesta di sostegno è stata modificata.";
$support_new = "Nuove Richieste Di Sostegno";
$support_noassigned = "Nessun richieste assegnate di sostegno";
$support_nonew = "Nessun nuove richieste di sostegno";
$support_received = "La vostra richiesta di sostegno è stata ricevuta e sarà assegnata ad un membro della nostra squadra di sostegno appena possibile.";
$support_regards = "Riguardi,";
$support_resolved = "La vostra richiesta di sostegno è stata risolta. Grazie per usando il nostro sistema del biglietto di sostegno.";
$support_submit = "Grazie per la presentazione della vostra richiesta di sostegno. Il vostro numero del biglietto è:";
$support_team = "Squadra Di Sostegno";
$support_thankyou = "Grazie per usando il nostro sistema del biglietto di sostegno";

$time = "Tempo:";

$ticketnumber = "Numero Del Biglietto:";

$update = "Aggiornamento";
$usernamemsg = "Username:";
$username_notfound = "Username non trovato.";

$variables_modified = "Variabili Modificato";

$viewticket = "Biglietto Di Vista";

$webaddress = "URL:";

$yes = "Sì";

?>