<?php

$access_denied = "Acceso denegado";

$activationemail_password = "Su contraseña elegida";
$activationemail_sent = "El email de la activación envió";

$add = "Agregar";

$back = "Atrás";

$date = "Fecha:";
$details = "Detalles:";
$domainmsg = "Dominio:";

$user_taken = "Error, nombre de usuario en uso. Elija otro, por favor.";

$client_activated = "Cliente activado.";
$client_added = "Cliente añadido.";
$client_cancelled = "Cliente dado de baja.";
$client_confdel = "Está usted seguro de que desea eliminar este cliente?";
$client_deleted = "Cliente eliminado.";
$client_duedate = "Fecha de vencimiento del pago del cliente ID:";
$client_edited = "Registro modificado.";
$client_email = "Email enviado a todos los clientes.";
$client_emailsent = "Se ha enviado un email a";
$client_error = "Error, no puedo recuperar los detalles del cliente.";
$client_id = "Cliente ID:";
$client_modifypass = "Password modificado.";
$client_noinvoice = "No hay clientes pendientes de facturar";
$client_nopending = "No hay clientes pendientes";
$client_notactivated = "Cliente No activado. Por favor complete todos los campos requeridos.";
$client_notadded = "Cliente No añadido. Por favor complete todos los campos requeridos.";
$client_notfound = "Cliente ID no encontrado.";
$client_nopending = "No hay clientes pendientes de activar.";
$client_unpaid = "No hay clientes pendientes de pago.";
$client_updated = "Los registros del cliente han sido actualizados.";
$client_updatedmsg = "Sus datos de contacto han sido actualizados.";

$company_biannual = "Número total de clientes semestrales:";
$company_biannualincome = "Renta total de clientes semestrales:";
$company_clients = "Número total de clientes:";
$company_monthly = "Número total de clientes mensuales:";
$company_monthlyincome = "Renta total de clientes mensuales:";
$company_quarterly = "Número total de clientes trimestrales:";
$company_quarterlyincome = "Renta total de clientes trimestrales:";
$company_statistics = "Estadísticas de la compañía";
$company_totalincome = "Ingresos totales anuales:";
$company_yearly = "Número total de clientes anuales:";
$company_yearlyincome = "Renta total de clientes anuales:";

$dealtby = "Negociado por:";

$descriptionmsg = "Descripción:";

$domain_notfound = "Dominio no encontrado.";

$duedatemsg = "Fecha de vencimiento del pago:";

$edit = "Editar";

$email_activation = "El email de activación de la cuenta ha sido modificado.";
$email_adminamend = "El email de soporte de administración ha sido modificado.";
$email_cancellation = "El email de la cuenta de cancelación ha sido modificado.";
$email_chequeconfirmation = "El email de confirmación de cheque ha sido modificado.";
$email_clientamend = " Se ha modificado el cliente enmienda el email de la ayuda .";
$email_closesupport = "Se ha modificado el email cercano de la ayuda.";
$email_ccconfirmation = "El email de confirmación de tarjeta de crédito ha sido modificado.";
$email_invoice = "Se ha modificado el email de la factura.";
$email_moniesconfirmation = "Se ha modificado el email de la confirmación de los dineros.";
$emailmsg = "Email:";
$email_neworder = "Email de nuevo pedido ha sido modificado.";
$email_nochexconfirmation = "Email de confirmación de NOCHEX ha sido modificado.";
$email_ordercancellation = "Email de cancelación de pedido ha sido modificado.";
$email_paypalconfirmation = "Email de confirmación de PayPal ha sido modificado.";
$email_receipt = "Email del recibo ha sido modificado.";
$email_submitted = "El email ha sido enviado. Contestaremos a su email en el plazo más breve posible.";
$email_support = "Se ha modificado el email nuevo de la ayuda.";
$email_supportnotice = "Email de petición de ayuda ha sido modificado.";

$fillfields = "Por favor complete todos los campos requeridos.";

$invoice_amount = "Importe vencido:";
$invoice_amountreceived = "Importe Recibido:";
$invoice_changedate = "Fecha de factura del cliente ID:";
$invoice_changed = "ha sido modificado.";
$invoice_date = "Fecha de la factura:";
$invoice_duedate = "Fecha de vencimiento del pago:";
$invoice_message = "A continuación puede ver un resumen de su factura. Una copia ha sido enviada por mail. Por favor haga su pago antes de la fecha de vencimiento, de otro modo su cuenta podría ser suspendida, hasta que el importe total sea abonado. Si usted paga mediante PayPal o tarjeta de crédito, no es necesario que haga nada más.";
$invoice_method = "Forma de pago:";
$invoice_notification = "Notificación de la factura";
$invoice_query = "Si tiene alguna duda, o no es capaz de pagar esta factura, por favor contactenos enviado una petición de soporte lo antes posible.";
$invoice_receipt = "Recibo del cliente";
$invoice_receiptmsg = "Este recibo es para confirmar que se ha recibido su pago. Una copia del mismo ha sido enviada por mail.";
$invoice_regards = "Atentamente,";
$invoice_schedule = "Horario De Pago:";
$invoice_sent = "Factura del cliente enviada.";
$invoice_thankyou = "Gracias por su confianza,";

$links_ccmodified = "Conexiones De la Tarjeta De Crédito Modificadas";
$links_nochexmodified = "Conexiones De Nochex Modificadas";
$links_paypalmodified = "Conexiones De PayPal Modificadas";

$login_error = "Error: ha introducido una combinación incorrecta de Usuario/Password.";
$login_pass = "Por favor, introduzca su Password.";
$login_thankyou = "Gracias por acceder al sistema";
$login_user = "Por favor, introduzca su nombre de usuario.";
$login_userpass = "Por favor, introduzca su Usuario y Password.";

$newduedate = "Introduzca la nueva fecha de vencimiento del pago";
$newinvoicedate = "Introduzca la nueva fecha de la factura";
$newticket = "Nuevo ticket";

$no = "No";

$notransactions = "No hay transacciones en esta fecha.";
$notransactionsmsg = "Usted no tiene ninguna transacción.";

$packagemsg = "Paquete:";

$plan_added = "Plan Agregado";
$plan_deleted = "Plan Suprimido";
$plan_modified = "Plan Modificado";
$plan_name = "Incorpore por favor el nombre del plan";

$search = "Búsqueda";

$searchtransactiondate = "Buscar por fecha:";

$showallmsg = "Mostrar todo";

$staff_added = "Miembro del equipo añadido.";
$staff_deleted = "Miembro del equipo ha sido eliminado.";
$staff_edited = "Miembro del equipo modificado.";
$staff_error = "Error, incapaz extraer a detalles del personal.";
$staff_modifypass = "Password moficado.";
$staff_notadded ="Miembro del equipo no añadido. Por favor, complete los campos requeridos.";
$staff_notfound = "ID de miembro del equipo no encontrado.";

$statusmsg = "Estatus:";

$subjectmsg = "Asunto:";

$support_assigned = "Peticiones de ayuda asignadas";
$support_close = "Ticket cerrado";
$support_closed = "Petición ayuda cerrada.";
$support_closedmsg = "Esta petición de ayuda ha sido cerrada.";
$support_description = "Agregue a la descripción";
$support_email = "Un email ha sido enviado a la dirección email facilitada.";
$support_enter = "Por favor, añada su modificación a la petición de ayuda.";
$support_error = "Error, no puedo encontrar el número de ticket. Por favor introduzcalo de nuevo.";
$support_fields = "Por favor, complete todos los campos requeridos.";
$support_modified = "La petición de ayuda ha sido modificada.";
$support_new = "Nuevas peticiones de ayuda";
$support_noassigned = "No hay peticios de ayuda asignadas";
$support_nonew = "No hay nuevas peticiones de ayuda";
$support_received = "Su petición de ayuda ha sido recibida y será asignada a un miembro del equipo de soporte cuanto antes .";
$support_regards = "Atentamente,";
$support_resolved = "Su petición de ayuda ha sido resuelta. Gracias por utilizar nuestro sistema de ayuda.";
$support_submit = "Gracias por enviar su petición de ayuda. Su número de boleto es:";
$support_team = "Departamento de soporte";
$support_thankyou = "Gracias por utilizar nuestro sistema de ayuda";

$time = "Tiempo:";

$ticketnumber = "Número de ticket:";

$update = "Actualizar";
$usernamemsg = "Nombre de usuario:";
$username_notfound = "Nombre de usuario no encontrado.";

$variables_modified = "Variables Modificadas";

$viewticket = "Ver ticket";

$webaddress = "URL:";

$yes = "Si";

?>