# the following entry needs to be made in the PostgreSQL User Admin table
# relata = the Relata user
# SysID  = automatically generated by PostgreSQL

#Username 	SysID 	Create DB 	Super User 	Expires 
relata 		## 	No 		Yes 		2038-01-18 00:00:00-08 

