<?php

/*======================================================================*\
|| #################################################################### ||
||  Program Name         : VirtuaNews Pro                                 
||  Release Version      : 1.0.3                                          
||  Program Author       : VirtuaSystems                                  
||  Supplied by          : Ravish                                         
||  Nullified by         : WTN Team                                       
||  Distribution         : via WebForum, ForumRU and associated file dumps
|| #################################################################### ||
\*======================================================================*/

if (preg_match("/(admin\/log.php)/i",$PHP_SELF)) {
  header("location:../admin.php");
  exit;
}

function checklogperms() {

  global $admindirectory;

  include("$admindirectory/config.php");

  global $staffid;
  if ($canprunelog == "") {
    return 0;
  } else {
    $permlist = trim($canprunelog);
    if (strstr($permlist,",")) {
      $validusers = explode(",",$permlist);
      $continue = 0;
      foreach ($validusers AS $value) {
        if ($staffid == intval($value)) {
          $continue = 1;
          break;
        }
      }
      if ($continue) {
        return 1;
      } else {
        return 0;
      }
    } else {
      if ($staffid == intval($permlist)) {
        return 1;
      } else {
        return 0;
      }
    }
  }
}

updateadminlog();

switch ($action) {

case "log":

  $userselect = "\n      <select name=\"staff\" class=\"form\">\n        <option value=\"0\">---------All---------</option>\n";

  $getstaff = query("SELECT news_staff.id,".$foruminfo[user_table].".".$foruminfo[username_field]." AS username FROM news_staff LEFT JOIN $foruminfo[user_table] ON news_staff.userid = ".$foruminfo[user_table].".".$foruminfo[userid_field]." ORDER BY ".$foruminfo[user_table].".".$foruminfo[username_field]);

  while ($staff_arr = fetch_array($getstaff)) {
    $userselect .= "        <option value=\"$staff_arr[id]\">$staff_arr[username]</option>\n";
  }

  $userselect .= "      </select>\n    ";


  $fileselect = "\n      <select name=\"script\" class=\"form\">\n        <option value=\"\">--------All--------</option>\n";

  $adminhandle = opendir("$admindirectory/");

  while ($file = readdir($adminhandle)) {
    if (($file != "config.php") & preg_match("/php$/",$file)) {
      $filename = explode(".",$file);
      $fileselect .= "        <option value=\"$filename[0]\">$file</option>\n";
    }
  }
  closedir($adminhandle);


  $fileselect .= "        <option value=\"\"></option>\n";
  $fileselect .= "        <option value=\"\">------Modules------</option>\n";

  $moddata = getmoddata();
  while ($mod_arr = fetch_array($moddata)) {
    $fileselect .= "        <option value=\"$mod_arr[name]\">$mod_arr[name]</option>\n";
  }

  $fileselect .= "      </select>\n    ";

  echohtmlheader();
  echoformheader("log_show","View $sitename Admin Log");
  echotabledescription("Use this page to view the admin log produced by the VirtuaNews admin panel");
  echotablerow("View entries created by:",$userselect);
  echotablerow("View entries generated by:",$fileselect);
  echoinputcode("Entries to display per page:","perpage",25,20);
  echotablerow("Order Entries by:","\n      <select name=\"order_by\" class=\"form\">
        <option value=\"date\">Date</option>
        <option value=\"staff\">Staff Name</option>
        <option value=\"script\">Script</option>
      </select>\n    ");
  echoyesnocode("Order Direction:","order_dir",0,"Ascending","Descending");
  echoformfooter();

  if (checklogperms() == 1) {

    echoformheader("log_prune","Prune Admin Log");
    echotabledescription("Use this form to prune the admin log entries from the database.");
    echotablerow("Remove entries created by:",$userselect);
    echotablerow("Remove entries generated by:",$fileselect);
    echoinputcode("Remove entries older than x days:","numdays",30);
    echoformfooter();
  }

  echohtmlfooter();

break;

case "log_show":

  unset($sql_arr);
  unset($sqlcondition);

  if ($script != "") {
    $sql_arr[] = "(news_adminlog.script = '$script')";
  }

  if ($staff != 0) {
    $sql_arr[] = "(news_adminlog.staffid = ".intval($staff).")";
  }

  if ($sql_arr) {
    $sqlcondition = " WHERE ".join(" AND ",$sql_arr);
  }

  if ($order_dir) {
    $direction = "";
  } else {
    $direction = " DESC";
  }

  switch ($order_by) {
  case "staff":
    $order = $foruminfo[user_table].".".$foruminfo[username_field]."$direction,news_adminlog.time DESC";
  break;
  case "script":
    $order = "news_adminlog.script$direction,news_adminlog.time DESC";
  break;
  default:
    $order = "news_adminlog.time$direction";
  }

  settype($perpage,"integer");
  settype($pagenum,"integer");

  if ($perpage < 1) {
    $perpage = 25;
  }

  if ($pagenum < 1) {
    $pagenum = 1;
  }

  $offset = ($pagenum - 1) * $perpage;

  $numrecords = query_first("SELECT COUNT(id) AS count FROM news_adminlog$sqlcondition");
  $numrecords = $numrecords[count];

  $pagenav = pagenav($perpage,$pagenum,"admin.php?action=log_show&staff=$staff&script=$script&order_by=$order_by&order_dir=$order_dir",$numrecords);

  echohtmlheader();
  echotableheader("View Admin Log",1);
  echotabledescription(returnlinkcode("Search Again","admin.php?action=log"),1);

  $tablerows = returnminitablerow("<b>Log ID</b>",returnlinkcode("<b>Staff Name</b>","admin.php?action=log_show&staff=$staff&script=$script&order_by=staff&order_dir=$order_dir&pagenum=$pagenum&perpage=$perpage"),returnlinkcode("<b>Date</b>","admin.php?action=log_show&staff=$staff&script=$script&order_by=date&order_dir=$order_dir&pagenum=$pagenum&perpage=$perpage"),returnlinkcode("<b>Script</b>","admin.php?action=log_show&staff=$staff&script=$script&order_by=script&order_dir=$order_dir&pagenum=$pagenum&perpage=$perpage"),"<b>Action</b>","<b>Extra Info</b>","<b>IP Address</b>");

  $getdata = query("SELECT
    news_adminlog.id,
    news_adminlog.time,
    news_adminlog.script,
    news_adminlog.action,
    news_adminlog.extrainfo,
    news_adminlog.ipaddress,
    ".$foruminfo[user_table].".".$foruminfo[username_field]." AS username
    FROM news_adminlog
    LEFT JOIN news_staff ON news_adminlog.staffid = news_staff.id
    LEFT JOIN $foruminfo[user_table] ON news_staff.userid = ".$foruminfo[user_table].".".$foruminfo[userid_field]."
    $sqlcondition
    ORDER BY $order
    LIMIT $offset,$perpage");

  while ($data_arr = fetch_array($getdata)) {
    $tablerows .= returnminitablerow($data_arr[id],$data_arr[username],date("H:i, jS M Y",$data_arr[time]-$timeoffset),$data_arr[script],"$data_arr[action]&nbsp;","$data_arr[extrainfo]&nbsp;",$data_arr[ipaddress]);
  }

  echotabledescription("\n".returnminitable($tablerows,0,100)."    ",1);
  echotabledescription($pagenav,1);
  echotablefooter();
  echohtmlfooter();

break;

case "log_prune":

  if (checklogperms() == 0) {
    adminerror("No permissions","You do not have the correct permissions to prune the admin log");
  }

  settype($numdays,"integer");
  if ($numdays == 0) {
    adminerror("Invalid Data","The number of days you have entered is not valid, it must be a valid integer");
  }

  unset($sql_arr);
  unset($sqlcondition);

  if ($script != "") {
    $sql_arr[] = "(news_adminlog.script = '$script')";
  }

  if ($staff != 0) {
    $sql_arr[] = "(news_adminlog.staffid = ".intval($staff).")";
  }

  $sql_arr[] = "(time < '".(time()-($numdays*86400))."')";

  $sqlcondition = " WHERE ".join(" AND ",$sql_arr);

  query("DELETE FROM news_adminlog$sqlcondition");

  echohtmlheader();
  echotableheader("Admin Log Pruned",1);
  echotabledescription("Pruning of the admin log is now complete.  Please click <a href=\"admin.php?action=log\">here</a> to return back to the admin log.",1);
  echotablefooter();
  echohtmlfooter();

break;

case "log_server":

  $getstats = query("SELECT name,type,value FROM news_useragent ORDER BY type,value DESC,name");
  while ($stats = fetch_array($getstats)) {

    if ($stats[type] == "browser") {
      $browser_arr[$stats[name]] = $stats[value];
    } elseif ($stats[type] == "os") {
      $os_arr[$stats[name]] = $stats[value];
    }
  }

  $STATS = query_first('SELECT * FROM news_stats');

  $countusers = query_first('SELECT COUNT(*) AS count FROM news_hit WHERE time > ' . (time() - $sessiontimeout));

  $STATS['usersonline'] = $countusers['count'];
  extract($STATS, EXTR_SKIP);

  echohtmlheader();
  echotableheader("Visitor Numbers For $sitename");

  if ($dositestats) {
    echotablerow("<b>Uniques today:</b>","<span class=\"red\">$uniquestoday</span>","",20);
    echotablerow("<b>Uniques total:</b>","<span class=\"red\">$uniquestotal</span>","",20);
    echotablerow("<b>Users online:</b>","<span class=\"red\">$usersonline</span>","",20);
    echotablerow("<b>Max users online:</b>","<span class=\"red\">$maxusersonline</span>","",20);
  } else {
    echotabledescription("Disabled in the site options");
  }

  echotablefooter();
  echo "<br />\n";
  echotableheader("Visitor's Browsers");

  if ($dositestats) {
    foreach ($browser_arr AS $name => $value) {
      $percent = @round(($value/$uniquestotal)*100);
      $barwidth = @round(($value/$uniquestotal)*200);
      echotablerow("<b>$name:</b>","<img src=\"$admindirectory/icons/bar.gif\" height=\"11\" width=\"$barwidth\" alt=\"\" /> <span class=\"red\">$percent% ($value)</span>","",20);
    }
  } else {
    echotabledescription("Disabled in the site options");
  }

  echotablefooter();
  echo "<br />\n";
  echotableheader("Visitor's Operating Systems");

  if ($dositestats) {
    foreach ($os_arr AS $name => $value) {
      $percent = @round(($value/$uniquestotal)*100);
      $barwidth = @round(($value/$uniquestotal)*200);
      echotablerow("<b>$name:</b>","<img src=\"$admindirectory/icons/bar.gif\" height=\"11\" width=\"$barwidth\" alt=\"\" /> <span class=\"red\">$percent% ($value)</span>","",20);
    }
  } else {
    echotabledescription("Disabled in the site options");
  }

  echotablefooter();
  echo "<br />\n";
  echotableheader("HTTP Referers");

  if ($dohttpreferer) {

    $getreferers = query("SELECT name,value FROM news_referer ORDER BY value DESC,name");
    while ($referer = fetch_array($getreferers)) {

      $percent = @round(($referer[value]/$uniquestotal)*100);
      $barwidth = @round(($referer[value]/$uniquestotal)*200);
      echotablerow("<b>$referer[name]:</b>","<img src=\"$admindirectory/icons/bar.gif\" height=\"11\" width=\"$barwidth\" alt=\"\" /> <span class=\"red\">$percent% ($referer[value])</span>","",20);

    }
  } else {
    echotabledescription("Disabled in the site options");
  }

  echotablefooter();
  echohtmlfooter();

break;

case "log_post":

  echohtmlheader();
  echoformheader("log_post_show","View Post Statistics");
  echotablerow("Type of Statistics:","\n      <select name=\"what\" class=\"form\">
        <option value=\"posts\">  News Posts  </option>
        <option value=\"comments\">  Comments  </option>
      </select>\n    ");
  echodatecode("Date From:","from",time()-3600*24*90);
  echodatecode("Date To:","to",time()+3600*24);
  echotablerow("Time Frame:","\n      <select name=\"timeframe\" class=\"form\">
        <option value=\"day\">  Daily  </option>
        <option value=\"week\">  Weekly  </option>
        <option value=\"month\">  Monthly  </option>
      </select>\n    ");
  echoyesnocode("Sort Dates:","sort",1,"Ascending","Descending");
  echoformfooter();
  echohtmlfooter();

break;

case "log_post_show":

  $table = iif($what == "comments","news_comment","news_news");
  $direction = iif($sort,""," DESC");
  $to = mktime(12,0,0,$tomonth,$today,$toyear);
  $from = mktime(12,0,0,$frommonth,$fromday,$fromyear);

  if ($timeframe == "day") {
    $sqlformat = "%w %U %m %Y";
    $phpformat = "F dS, Y";
  } elseif ($timeframe == "week") {
    $sqlformat = "%U %Y";
    $phpformat = "# (F Y)";
  } elseif ($timeframe == "month") {
    $sqlformat = "%m %Y";
    $phpformat = "F Y";
  }

  $stats = query("SELECT COUNT(*) AS count,DATE_FORMAT(FROM_UNIXTIME(time),'$sqlformat') AS timeframe, MAX(time) AS maxvalue FROM $table WHERE (time > '$from') AND (time < '$to') GROUP BY timeframe ORDER BY time$direction");

  while ($stat = fetch_array($stats)) {

    $stat_arr[$stat[maxvalue]] = $stat[count];

    $total += $stat[count];
  }

  echohtmlheader();
  echotableheader("Post Statistics");

  if ($stat_arr) {
    foreach ($stat_arr AS $key => $val) {

      $percent = @round(($val/$total)*100);
      $barwidth = @round(($val/$total)*200);

      echotablerow("<b>".str_replace("#","Week ".strftime("%W",$key),date($phpformat,$key)).":</b>","<img src=\"$admindirectory/icons/bar.gif\" height=\"11\" width=\"$barwidth\" alt=\"\" /> <span class=\"red\">$percent% ($val)</span>","",20);
    }
  }

  echotablefooter();
  echohtmlfooter();

break;

default:
  adminerror("Invalid Link","You have followed an invalid link");
}

/*======================================================================*\
|| ####################################################################
|| # File: admin/log.php
|| ####################################################################
\*======================================================================*/

?>