CREATE TABLE `stickybeak_logs` (
  `ID` int(11) NOT NULL auto_increment,
  `sessionID` varchar(32) NOT NULL default '',
  `LOGYEAR` smallint(6) NOT NULL default '0',
  `LOGMONTH` tinyint(6) NOT NULL default '0',
  `LOGDAY` tinyint(4) NOT NULL default '0',
  `LOGHOUR` tinyint(4) NOT NULL default '0',
  `LOGMINUTE` tinyint(4) NOT NULL default '0',
  `LOGSECOND` tinyint(4) NOT NULL default '0',
  `REMOTE_ADDR` varchar(15) NOT NULL default '',
  `HTTP_REFERER` tinytext,
  `REQUEST_METHOD` varchar(15) default NULL,
  `unixtime` int(11) NOT NULL default '0',
  `mysqltime` datetime NOT NULL default '0000-00-00 00:00:00',
  `HTTP_USER_AGENT` tinytext,
  `REMOTE_PORT` smallint(9) default NULL,
  `SCRIPT_NAME` tinytext,
  `HTTP_CONNECTION` tinytext,
  `HTTP_ACCEPT_LANGUAGE` tinytext,
  `HTTP_ACCEPT` text,
  `QUERY_STRING` tinytext,
  `SERVER_PROTOCOL` tinytext,
  `GATEWAY_INTERFACE` tinytext,
  `REMOTE_HOST_NAME` tinytext,
  `DOCUMENT_URL` varchar(255) NOT NULL default '',
  `HTTP_HOST` varchar(255) NOT NULL default '',
  `REQUEST_URI` varchar(255) NOT NULL default '',
  `page` varchar(32) NOT NULL default '',
  `identifier` varchar(32) NOT NULL default '',
  PRIMARY KEY  (`ID`)
) TYPE=MyISAM;
