<div id="topdivision">
<table width="750" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="192" valign="top" rowspan="2"><a href="main.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/logo.gif" border="0" width="192" height="131"></a></td>
<td width="496" valign="top"><img src="../templates/<?php echo $template ?>/images/banner.gif" width="496" height="119"></td>
<td width="77" valign="top"><img src="../templates/<?php echo $template ?>/images/bannerend.gif" width="77" height="119"></td>
</tr>
</table>
</div>