<table width="570" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="570" height="360" align="center" class="main">
<form method="post" action="<?php echo $PHP_SELF ?>">
<table border="0" cellspacing="0" cellpadding="2">
<tr>
<td align="right" class="main">
Username: <input type="text" class="formfield" name="adminname">
</td>
</tr>
<tr>
<td align="right" class="main">
Password: <input type="password" class="formfield" name="password">
</td>
</tr>
<tr>
<td align="center">
<input type="Submit" name="submit" value="Login" class="formfield">
</td>
</tr>
</table>
</form>
</td>
</tr>
</table>