<div id="leftdivision">
<table width="123" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="120" height="426" align="center" valign="top" background="../templates/<?php echo $template ?>/images/menubarbg.gif">
<table width="120" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="120">
<img src="../templates/<?php echo $template ?>/images/admincp.gif" width="120" height="40">
<a href="staffmanager/addstaff.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/addstaff.gif" border="0" width="120" height="25"></a>
<a href="email.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/editemail.gif" border="0" width="120" height="25"></a>
<a href="setup.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/setup.gif" border="0" width="120" height="25"></a>
<a href="statistics.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/statistic.gif" border="0" width="120" height="25"></a>
<a href="transactions.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/transaction.gif" border="0" width="120" height="25"></a>
<a href="staffmanager/viewstaff.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/viewstaff.gif" border="0" width="120" height="25"></a>
</td>
</tr>
</table>
<table width="120" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="120">
<img src="../templates/<?php echo $template ?>/images/clientmanager.gif" width="120" height="40">
<a href="clientmanager/add.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/addclient.gif" border="0" width="120" height="25"></a>
<a href="clientmanager/viewclients.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/viewclient.gif" border="0" width="120" height="25"></a>
</td>
</tr>
</table>
<table width="120" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="120">
<img src="../templates/<?php echo $template ?>/images/supportdesk.gif" width="120" height="40">
<a href="support/support.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/clientsupport.gif" border="0" width="120" height="25"></a>
<a href="clientmanager/message.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/sendmessage.gif" border="0" width="120" height="25"></a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="123">
<img src="../templates/<?php echo $template ?>/images/menubarend.gif" width="123" height="99">
</td>
</tr>
</table>
</div>