<div id="leftdivision">
<table width="123" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="120" height="426" align="center" valign="top" background="../templates/<?php echo $template ?>/images/menubarbg.gif">
<table width="120" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="120">
<img src="../templates/<?php echo $template ?>/images/supportdesk.gif" width="120" height="40">
<a href="support/support.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/clientsupport.gif" border="0" width="120" height="25"></a>
<a href="clientmanager/message.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/sendmessage.gif" border="0" width="120" height="25"></a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="123">
<img src="../templates/<?php echo $template ?>/images/menubarend.gif" width="123" height="99">
</td>
</tr>
</table>
</div>