
DROP TABLE IF EXISTS MOLINS_log;

CREATE TABLE MOLINS_log (
	creation_date TIMESTAMP NOT NULL,
	level VARCHAR(20) NOT NULL,
	message VARCHAR(240) NOT NULL,
	exception VARCHAR(240) NOT NULL
	
) TYPE = InnoDB;


DROP TABLE IF EXISTS media_category;

CREATE TABLE media_category (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	
		PRIMARY KEY (id)
) TYPE = InnoDB;

DROP TABLE IF EXISTS media;

CREATE TABLE media (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	media_id INT UNSIGNED NOT NULL REFERENCES media_category,
	content_type VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	size DOUBLE NOT NULL DEFAULT 0,
	data MEDIUMBLOB NOT NULL,
	
		PRIMARY KEY (id)
) TYPE = InnoDB;

