<div id="leftdivision">
<table width="123" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="123" height="426" align="center" valign="top" background="../templates/<?php echo $template ?>/images/menubarbg.gif">
<table width="120" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="120">
<img src="../templates/<?php echo $template ?>/images/accountcp.gif" width="120" height="40">
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/cron/index.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/cronjobs.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/mail/email.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/email.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/err/index.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/errorpages.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/ftp/index.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/ftpmanager.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/sql/index.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/mysql.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/subdomain/index.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/subdomains.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/submit/index.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/submitsite.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/telnet/index.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/telnet.gif" border="0" width="120" height="25"></a>
<a href="transactions.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/transaction.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/htaccess/index.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/webprotect.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/stats/webalizer.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/webstats.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/neomail/neomail.pl" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/webmail.gif" border="0" width="120" height="25"></a>
<a href="details.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/profile.gif" border="0" width="120" height="25"></a>
</td>
</tr>
</table>
<table width="120" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="120">
<img src="../templates/<?php echo $template ?>/images/controlpanel.gif" width="120" height="40">
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>/cpanel/" target="_blank" class="menulink"><img src="../templates/<?php echo $template ?>/images/cpanel4.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/3rdparty/phpMyAdmin/index.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/phpmyadmin.gif" border="0" width="120" height="25"></a>
</td>
</tr>
</table>
<table width="120" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="120">
<img src="../templates/<?php echo $template ?>/images/support.gif" border="0" width="120" height="40">
<a href="support.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/index.gif" border="0" width="120" height="25"></a>
<a href="http://<?php echo $clientname ?>:<?php echo $cpid ?>@<?php echo $domainname ?><?php echo $domain ?>:2082/frontend/iconic/backup/index.html" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/backups.gif" border="0" width="120" height="25"></a>
<a href="http://www.YOURFORUM.COM" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/forum.gif" border="0" width="120" height="25"></a>
<a href="support/support.php" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/helpdesk.gif" border="0" width="120" height="25"></a>
<a href="http://www.YOURSTATUSPAGE.COM" target="clients" class="menulink"><img src="../templates/<?php echo $template ?>/images/serverstatus.gif" border="0" width="120" height="25"></a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="123">
<img src="../templates/<?php echo $template ?>/images/menubarend.gif" width="123" height="99">
</td>
</tr>
</table>
</div>